# Generated by Django 3.2.25 on 2024-10-21 14:57

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import osis_document.contrib.fields
import parcours_doctoral.models.cdd_config
import uuid
from parcours_doctoral.mail_templates import (
    ADMISSION_EMAIL_CANDIDATE_COMPLEMENTARY_TRAINING_NEEDS_UPDATE,
    ADMISSION_EMAIL_CANDIDATE_COMPLEMENTARY_TRAINING_REFUSED,
    ADMISSION_EMAIL_CANDIDATE_COURSE_ENROLLMENT_NEEDS_UPDATE,
    ADMISSION_EMAIL_CANDIDATE_COURSE_ENROLLMENT_REFUSED,
    ADMISSION_EMAIL_CANDIDATE_DOCTORAL_TRAINING_NEEDS_UPDATE,
    ADMISSION_EMAIL_CANDIDATE_DOCTORAL_TRAINING_REFUSED,
    ADMISSION_EMAIL_REFERENCE_PROMOTER_COMPLEMENTARY_TRAININGS_SUBMITTED,
    ADMISSION_EMAIL_REFERENCE_PROMOTER_COURSE_ENROLLMENTS_SUBMITTED,
    ADMISSION_EMAIL_REFERENCE_PROMOTER_DOCTORAL_TRAININGS_SUBMITTED,
)

from osis_mail_template import MailTemplateMigration


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admission', '0227_auto_20241021_1455'),
        ('base', '0703_auto_20240926_1738'),
        ('reference', '0018_country_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='JuryMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('role', models.CharField(choices=[('PRESIDENT', 'PRESIDENT'), ('SECRETAIRE', 'SECRETAIRE'), ('MEMBRE', 'MEMBRE')], max_length=50, verbose_name='Role')),
                ('other_institute', models.CharField(blank=True, default='', max_length=255, verbose_name='Other institute')),
                ('institute', models.CharField(blank=True, default='', max_length=255, verbose_name='Institute')),
                ('last_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Surname')),
                ('first_name', models.CharField(blank=True, default='', max_length=255, verbose_name='First name')),
                ('title', models.CharField(blank=True, choices=[('DOCTEUR', 'Doctor'), ('PROFESSEUR', 'Professor'), ('NON_DOCTEUR', 'Does not have a doctor title')], default='', max_length=50, verbose_name='Title')),
                ('non_doctor_reason', models.TextField(blank=True, default='', max_length=255, verbose_name='Non doctor reason')),
                ('gender', models.CharField(blank=True, choices=[('FEMININ', 'Female'), ('MASCULIN', 'Male'), ('AUTRE', 'Other')], default='', max_length=50, verbose_name='Gender')),
                ('email', models.EmailField(blank=True, default='', max_length=255, verbose_name='Email')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reference.country', verbose_name='Country')),
                ('doctorate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jury_members', to='admission.doctorateadmission', verbose_name='PhD')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='base.person', verbose_name='Person')),
                ('promoter', models.ForeignKey(blank=True, limit_choices_to={'type': 'PROMOTER'}, null=True, on_delete=django.db.models.deletion.PROTECT, to='admission.supervisionactor', verbose_name='Supervisor')),
            ],
        ),
        migrations.CreateModel(
            name='ConfirmationPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('confirmation_date', models.DateField(blank=True, null=True, verbose_name='Confirmation exam date')),
                ('confirmation_deadline', models.DateField(blank=True, verbose_name='Confirmation deadline')),
                ('research_report', osis_document.contrib.fields.FileField(base_field=models.UUIDField(), default=list, size=1, verbose_name='Research report')),
                ('supervisor_panel_report', osis_document.contrib.fields.FileField(base_field=models.UUIDField(), default=list, size=1, verbose_name='Support Committee minutes')),
                ('supervisor_panel_report_canvas', osis_document.contrib.fields.FileField(base_field=models.UUIDField(), default=list, size=1, verbose_name='Canvas of the report of the supervisory panel')),
                ('research_mandate_renewal_opinion', osis_document.contrib.fields.FileField(base_field=models.UUIDField(), default=list, size=1, verbose_name='Opinion on research mandate renewal')),
                ('certificate_of_failure', osis_document.contrib.fields.FileField(base_field=models.UUIDField(), default=list, size=None, verbose_name='Certificate of failure')),
                ('certificate_of_achievement', osis_document.contrib.fields.FileField(base_field=models.UUIDField(), default=list, size=None, verbose_name='Certificate of achievement')),
                ('extended_deadline', models.DateField(blank=True, null=True, verbose_name='Deadline extended')),
                ('cdd_opinion', models.TextField(blank=True, default='', verbose_name='CDD opinion')),
                ('justification_letter', osis_document.contrib.fields.FileField(base_field=models.UUIDField(), default=list, size=None, verbose_name='Justification letter')),
                ('brief_justification', models.TextField(blank=True, default='', max_length=2000, verbose_name='Brief justification')),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admission.doctorateadmission', verbose_name='Admission')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='CddConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_complementary_training_enabled', models.BooleanField(default=False, help_text='This adds a "Complementary training" tab on admissions concerning this CDD.', verbose_name='Enable complementary training tab')),
                ('category_labels', parcours_doctoral.models.cdd_config.TranslatedMultilineField(default=parcours_doctoral.models.cdd_config.default_category_labels, verbose_name='Category labels')),
                ('conference_types', parcours_doctoral.models.cdd_config.TranslatedMultilineField(default=parcours_doctoral.models.cdd_config.default_conference_types, verbose_name='CONFERENCE types')),
                ('conference_publication_types', parcours_doctoral.models.cdd_config.TranslatedMultilineField(default=parcours_doctoral.models.cdd_config.default_conference_publication_types, verbose_name='CONFERENCE PUBLICATION types')),
                ('communication_types', parcours_doctoral.models.cdd_config.TranslatedMultilineField(default=parcours_doctoral.models.cdd_config.default_communication_types, verbose_name='COMMUNICATION types')),
                ('seminar_types', parcours_doctoral.models.cdd_config.TranslatedMultilineField(default=parcours_doctoral.models.cdd_config.default_seminar_types, verbose_name='SEMINAR types')),
                ('publication_types', parcours_doctoral.models.cdd_config.TranslatedMultilineField(default=parcours_doctoral.models.cdd_config.default_publication_types, verbose_name='PUBLICATION types')),
                ('service_types', parcours_doctoral.models.cdd_config.TranslatedMultilineField(default=parcours_doctoral.models.cdd_config.default_service_types, verbose_name='SERVICE types')),
                ('residency_types', parcours_doctoral.models.cdd_config.TranslatedMultilineField(default=parcours_doctoral.models.cdd_config.default_residency_types, verbose_name='RESIDENCY types')),
                ('course_types', parcours_doctoral.models.cdd_config.TranslatedMultilineField(default=parcours_doctoral.models.cdd_config.default_course_types, verbose_name='COURSE types')),
                ('complementary_course_types', parcours_doctoral.models.cdd_config.TranslatedMultilineField(default=parcours_doctoral.models.cdd_config.default_complementary_course_types, verbose_name='COURSE types for complementary training')),
                ('cdd', models.OneToOneField(limit_choices_to={'entityversion__entity_type': 'DOCTORAL_COMMISSION'}, on_delete=django.db.models.deletion.CASCADE, related_name='admission_config', to='base.entity')),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('context', models.CharField(choices=[('DOCTORAL_TRAINING', 'DOCTORAL_TRAINING'), ('COMPLEMENTARY_TRAINING', 'COMPLEMENTARY_TRAINING'), ('FREE_COURSE', 'FREE_COURSE')], default='DOCTORAL_TRAINING', max_length=30, verbose_name='Context')),
                ('ects', models.DecimalField(blank=True, decimal_places=1, default=0, help_text='Consult the credits grid released by your domain doctoral commission. Refer to the website of your commission for more details.', max_digits=3, validators=[django.core.validators.MinValueValidator(0)], verbose_name='ECTS credits')),
                ('status', models.CharField(choices=[('NON_SOUMISE', 'NON_SOUMISE'), ('SOUMISE', 'SOUMISE'), ('ACCEPTEE', 'ACCEPTEE'), ('REFUSEE', 'REFUSEE')], default='NON_SOUMISE', max_length=20)),
                ('category', models.CharField(choices=[('CONFERENCE', 'CONFERENCE'), ('COMMUNICATION', 'COMMUNICATION'), ('SEMINAR', 'SEMINAR'), ('PUBLICATION', 'PUBLICATION'), ('SERVICE', 'SERVICE'), ('RESIDENCY', 'RESIDENCY'), ('VAE', 'VAE'), ('COURSE', 'COURSE'), ('PAPER', 'PAPER'), ('UCL_COURSE', 'UCL_COURSE')], max_length=50)),
                ('type', models.CharField(blank=True, default='', max_length=100, verbose_name='Activity type')),
                ('title', models.CharField(blank=True, default='', max_length=200, verbose_name='Title')),
                ('participating_proof', osis_document.contrib.fields.FileField(base_field=models.UUIDField(), blank=True, default=list, size=1, verbose_name='Participation certification')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Comment')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Activity begin date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Activity end date')),
                ('participating_days', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Number of days participating')),
                ('is_online', models.BooleanField(blank=True, choices=[(False, 'In person'), (True, 'Online')], default=None, null=True, verbose_name='Online event')),
                ('city', models.CharField(blank=True, default='', max_length=100, verbose_name='City')),
                ('organizing_institution', models.CharField(blank=True, default='', max_length=100, verbose_name='Organising institution')),
                ('website', models.URLField(blank=True, default='', verbose_name='Website')),
                ('committee', models.CharField(blank=True, choices=[('YES', 'YES'), ('NO', 'NO'), ('NA', 'N/A')], default='', max_length=100)),
                ('dial_reference', models.CharField(blank=True, default='', max_length=100, verbose_name='Reference DIAL.Pr')),
                ('acceptation_proof', osis_document.contrib.fields.FileField(base_field=models.UUIDField(), blank=True, default=list, size=1, verbose_name='Participation certification')),
                ('summary', osis_document.contrib.fields.FileField(base_field=models.UUIDField(), blank=True, default=list, size=1, verbose_name='Summary')),
                ('subtype', models.CharField(blank=True, default='', max_length=100, verbose_name='Activity subtype')),
                ('subtitle', models.TextField(blank=True, default='')),
                ('authors', models.CharField(blank=True, default='', max_length=100, verbose_name='Authors')),
                ('role', models.CharField(blank=True, default='', max_length=100, verbose_name='Role')),
                ('keywords', models.CharField(blank=True, default='', max_length=100, verbose_name='Keywords')),
                ('journal', models.CharField(blank=True, default='', max_length=100, verbose_name='Journal or publishing house name')),
                ('publication_status', models.CharField(blank=True, choices=[('UNSUBMITTED', 'Unsubmitted for publication'), ('SUBMITTED', 'Submitted for publication'), ('IN_REVIEW', 'Awaiting approval'), ('ACCEPTED', 'Accepted'), ('PUBLISHED', 'Published')], default='', max_length=100)),
                ('hour_volume', models.CharField(blank=True, default='', max_length=100, verbose_name='Total hourly volume')),
                ('course_completed', models.BooleanField(blank=True, default=False)),
                ('reference_promoter_assent', models.BooleanField(null=True, verbose_name='Lead supervisor assent')),
                ('reference_promoter_comment', models.TextField(default='', verbose_name='Lead supervisor comment')),
                ('cdd_comment', models.TextField(default='', verbose_name='CDD manager comment')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('can_be_submitted', models.BooleanField(default=False, verbose_name='Can be submitted')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reference.country', verbose_name='Country')),
                ('doctorate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admission.doctorateadmission')),
                ('learning_unit_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='base.learningunityear')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='parcours_doctoral.activity')),
            ],
            options={
                'verbose_name': 'Training activity',
                'verbose_name_plural': 'Training activities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='jurymember',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('promoter__isnull', False), ('person__isnull', True), ('institute', ''), ('other_institute', ''), ('country__isnull', True), ('last_name', ''), ('first_name', ''), ('title', ''), ('gender', ''), ('email', '')), models.Q(('promoter__isnull', True), ('person__isnull', False), ('institute', ''), ('country__isnull', True), ('last_name', ''), ('first_name', ''), ('title', ''), ('gender', ''), ('email', '')), models.Q(('promoter__isnull', True), ('person__isnull', True), models.Q(('institute', ''), _negated=True), ('country__isnull', False), models.Q(('last_name', ''), _negated=True), models.Q(('first_name', ''), _negated=True), models.Q(('title', ''), _negated=True), models.Q(('gender', ''), _negated=True), models.Q(('email', ''), _negated=True)), _connector='OR'), name='admission_jurymember_constraint'),
        ),


        MailTemplateMigration(
            ADMISSION_EMAIL_REFERENCE_PROMOTER_DOCTORAL_TRAININGS_SUBMITTED,
            {
                'en': '[OSIS] New doctoral training activities been submitted by {student_first_name} {student_last_name}',
                'fr-be': "[OSIS] De nouvelles activités de formation doctorale ont été soumises par "
                "{student_first_name} {student_last_name}",
            },
            {
                'en': '''<p>Hello,</p>

    <p>
        {student_first_name} {student_last_name} have submitted new doctoral training activities for {training_title}, 
        you can review them by following this link: {admission_link_front_doctoral_training}.
    </p>

    <p>
        ---<br/>
        The OSIS Team
    </p>
    ''',
                'fr-be': '''<p>Bonjour,</p>

    <p>
        {student_first_name} {student_last_name} a soumis de nouvelles activités de formation doctorale 
        pour son {training_title}, vous pouvez les consulter en suivant ce lien : {admission_link_front_doctoral_training}.
    </p>

    <p>
        ---<br/>
        L'équipe OSIS
    </p>
    ''',
            },
        ),
        MailTemplateMigration(
            ADMISSION_EMAIL_CANDIDATE_DOCTORAL_TRAINING_REFUSED,
            {
                'en': '[OSIS] A doctoral training activity has been refused',
                'fr-be': "[OSIS] Une activité de formation doctorale a été refusée",
            },
            {
                'en': '''<p>Hello,</p>

    <p>
        The submitted doctoral training activity entitled <em>{activity_title}</em> for your {training_title} has been refused, 
        you can review all activities by following this link: {admission_link_front_doctoral_training}.

        Here's the reason for this refusal: {reason}
    </p>

    <p>
        ---<br/>
        The OSIS Team
    </p>
    ''',
                'fr-be': '''<p>Bonjour,</p>

    <p>
        L'activité de formation doctorale soumise intitulée <em>{activity_title}</em> pour votre {training_title} a été refusée,
        vous pouvez la consulter en suivant ce lien : {admission_link_front_doctoral_training}.

        La raison invoquée pour ce refus : {reason}
    </p>

    <p>
        ---<br/>
        L'équipe OSIS
    </p>
    ''',
            },
        ),
        MailTemplateMigration(
            ADMISSION_EMAIL_CANDIDATE_DOCTORAL_TRAINING_NEEDS_UPDATE,
            {
                'en': '[OSIS] A doctoral training activity needs to be updated',
                'fr-be': "[OSIS] Une activité de formation doctorale doit être mise à jour",
            },
            {
                'en': '''<p>Hello,</p>

    <p>
        The submitted doctoral training activity entitled <em>{activity_title}</em> for {training_title} must be updated, 
        you can review all activities by following this link: {admission_link_front_doctoral_training}.

        Here's why it needs to be updated: {reason}
    </p>

    <p>
        ---<br/>
        The OSIS Team
    </p>
    ''',
                'fr-be': '''<p>Bonjour,</p>

    <p>
        L'activité de formation doctorale soumise intitulée <em>{activity_title}</em> doit être mise à jour 
        pour {training_title}, vous pouvez la consulter en suivant ce lien : {admission_link_front_doctoral_training}.

        Voici ce pourquoi vous devez la modifier : {reason}
    </p>

    <p>
        ---<br/>
        L'équipe OSIS
    </p>
    ''',
            },
        ),
        MailTemplateMigration(
            ADMISSION_EMAIL_REFERENCE_PROMOTER_COMPLEMENTARY_TRAININGS_SUBMITTED,
            {
                'en': '[OSIS] New complementary training activities been submitted by '
                '{student_first_name} {student_last_name}',
                'fr-be': "[OSIS] De nouvelles activités de formation complémentaire ont été soumises par {student_first_name} "
                "{student_last_name}",
            },
            {
                'en': '''<p>Hello,</p>

    <p>
        {student_first_name} {student_last_name} have submitted new complementary training activities for {training_title}, 
        you can review them by following this link: {admission_link_front_complementary_training}.
    </p>

    <p>
        ---<br/>
        The OSIS Team
    </p>
    ''',
                'fr-be': '''<p>Bonjour,</p>

    <p>
        {student_first_name} {student_last_name} a soumis de nouvelles activités de formation complémentaire pour son {training_title},
        vous pouvez les consulter en suivant ce lien : {admission_link_front_complementary_training}.
    </p>

    <p>
        ---<br/>
        L'équipe OSIS
    </p>
    ''',
            },
        ),
        MailTemplateMigration(
            ADMISSION_EMAIL_CANDIDATE_COMPLEMENTARY_TRAINING_REFUSED,
            {
                'en': '[OSIS] A complementary training activity has been refused',
                'fr-be': "[OSIS] Une activité de formation complémentaire a été refusée",
            },
            {
                'en': '''<p>Hello,</p>

    <p>
        The submitted complementary training activity entitled <em>{activity_title}</em> for your {training_title} has been refused, 
        you can review all activities by following this link: {admission_link_front_complementary_training}.

        Here's the reason for this refusal: {reason}
    </p>

    <p>
        ---<br/>
        The OSIS Team
    </p>
    ''',
                'fr-be': '''<p>Bonjour,</p>

    <p>
        L'activité de formation complémentaire soumise intitulée <em>{activity_title}</em> pour votre {training_title} a été refusée,
        vous pouvez la consulter en suivant ce lien : {admission_link_front_complementary_training}.

        La raison invoquée pour ce refus : {reason}
    </p>

    <p>
        ---<br/>
        L'équipe OSIS
    </p>
    ''',
            },
        ),
        MailTemplateMigration(
            ADMISSION_EMAIL_CANDIDATE_COMPLEMENTARY_TRAINING_NEEDS_UPDATE,
            {
                'en': '[OSIS] A complementary training activity needs to be updated',
                'fr-be': "[OSIS] Une activité de formation complémentaire doit être mise à jour",
            },
            {
                'en': '''<p>Hello,</p>

    <p>
        The submitted complementary training activity entitled <em>{activity_title}</em> for {training_title} must be updated, 
        you can review them by following this link: {admission_link_front_complementary_training}.

        Here's why it needs to be updated: {reason}
    </p>

    <p>
        ---<br/>
        The OSIS Team
    </p>
    ''',
                'fr-be': '''<p>Bonjour,</p>

    <p>
        L'activité de formation complémentaire soumise intitulée <em>{activity_title}</em> doit être mise à jour pour {training_title},
        vous pouvez la consulter en suivant ce lien : {admission_link_front_complementary_training}.

        Voici ce pourquoi vous devez la modifier : {reason}
    </p>

    <p>
        ---<br/>
        L'équipe OSIS
    </p>
    ''',
            },
        ),
        MailTemplateMigration(
            ADMISSION_EMAIL_REFERENCE_PROMOTER_COURSE_ENROLLMENTS_SUBMITTED,
            {
                'en': '[OSIS] New course enrollments been submitted by {student_first_name} {student_last_name}',
                'fr-be': "[OSIS] Nouvelles inscriptions aux cours soumises par {student_first_name} "
                "{student_last_name}",
            },
            {
                'en': '''<p>Hello,</p>

    <p>
        {student_first_name} {student_last_name} have submitted new course enrollments for {training_title}, 
        you can review them by following this link: {admission_link_front_course_enrollment}.
    </p>

    <p>
        ---<br/>
        The OSIS Team
    </p>
    ''',
                'fr-be': '''<p>Bonjour,</p>

    <p>
        {student_first_name} {student_last_name} a soumis de nouvelles inscriptions aux cours pour son {training_title},
        vous pouvez les consulter en suivant ce lien : {admission_link_front_course_enrollment}.
    </p>

    <p>
        ---<br/>
        L'équipe OSIS
    </p>
    ''',
            },
        ),
        MailTemplateMigration(
            ADMISSION_EMAIL_CANDIDATE_COURSE_ENROLLMENT_REFUSED,
            {
                'en': '[OSIS] A course enrollment has been refused',
                'fr-be': "[OSIS] Une inscription à un cours a été refusée",
            },
            {
                'en': '''<p>Hello,</p>

    <p>
        The submitted course enrollment entitled <em>{activity_title}</em> for your {training_title} has been refused, 
        you can review all courses by following this link: {admission_link_front_course_enrollment}.

        Here's the reason for this refusal: {reason}
    </p>

    <p>
        ---<br/>
        The OSIS Team
    </p>
    ''',
                'fr-be': '''<p>Bonjour,</p>

    <p>
        Une inscription à un cours intitulé <em>{activity_title}</em> pour votre {training_title} a été refusée,
        vous pouvez la consulter en suivant ce lien : {admission_link_front_course_enrollment}.

        La raison invoquée pour ce refus : {reason}
    </p>

    <p>
        ---<br/>
        L'équipe OSIS
    </p>
    ''',
            },
        ),
        MailTemplateMigration(
            ADMISSION_EMAIL_CANDIDATE_COURSE_ENROLLMENT_NEEDS_UPDATE,
            {
                'en': '[OSIS] A course enrollment needs to be updated',
                'fr-be': "[OSIS] Une inscription à un cours doit être mise à jour",
            },
            {
                'en': '''<p>Hello,</p>

    <p>
        The submitted course enrollment entitled <em>{activity_title}</em> for {training_title} must be updated, 
        you can review all courses by following this link: {admission_link_front_course_enrollment}.

        Here's why it needs to be updated: {reason}
    </p>

    <p>
        ---<br/>
        The OSIS Team
    </p>
    ''',
                'fr-be': '''<p>Bonjour,</p>

    <p>
        Une inscription à un cours intitulé <em>{activity_title}</em> doit être mise à jour pour {training_title},
        vous pouvez la consulter en suivant ce lien : {admission_link_front_course_enrollment}.

        Voici ce pourquoi vous devez la modifier : {reason}
    </p>

    <p>
        ---<br/>
        L'équipe OSIS
    </p>
    ''',
            },
        ),
    ]
