# Generated by Django 4.2.16 on 2024-11-14 11:47

from django.db import migrations
from osis_mail_template import MailTemplateMigration

from parcours_doctoral.mail_templates import (
    PARCOURS_DOCTORAL_EMAIL_CONFIRMATION_PAPER_INFO_STUDENT,
    PARCOURS_DOCTORAL_EMAIL_CONFIRMATION_PAPER_ON_FAILURE_ADRE,
    PARCOURS_DOCTORAL_EMAIL_CONFIRMATION_PAPER_ON_FAILURE_ADRI,
    PARCOURS_DOCTORAL_EMAIL_CONFIRMATION_PAPER_ON_FAILURE_STUDENT,
    PARCOURS_DOCTORAL_EMAIL_CONFIRMATION_PAPER_ON_RETAKING_ADRE,
    PARCOURS_DOCTORAL_EMAIL_CONFIRMATION_PAPER_ON_RETAKING_ADRI,
    PARCOURS_DOCTORAL_EMAIL_CONFIRMATION_PAPER_ON_RETAKING_STUDENT,
    PARCOURS_DOCTORAL_EMAIL_CONFIRMATION_PAPER_ON_SUCCESS_ADRE,
    PARCOURS_DOCTORAL_EMAIL_CONFIRMATION_PAPER_ON_SUCCESS_ADRI,
    PARCOURS_DOCTORAL_EMAIL_CONFIRMATION_PAPER_ON_SUCCESS_STUDENT,
    PARCOURS_DOCTORAL_EMAIL_CONFIRMATION_PAPER_SUBMISSION_ADRE,
    PARCOURS_DOCTORAL_EMAIL_GENERIC,
    PARCOURS_DOCTORAL_EMAIL_REFERENCE_PROMOTER_COMPLEMENTARY_TRAININGS_SUBMITTED,
    PARCOURS_DOCTORAL_EMAIL_REFERENCE_PROMOTER_COURSE_ENROLLMENTS_SUBMITTED,
    PARCOURS_DOCTORAL_EMAIL_REFERENCE_PROMOTER_DOCTORAL_TRAININGS_SUBMITTED,
    PARCOURS_DOCTORAL_EMAIL_STUDENT_COMPLEMENTARY_TRAINING_NEEDS_UPDATE,
    PARCOURS_DOCTORAL_EMAIL_STUDENT_COMPLEMENTARY_TRAINING_REFUSED,
    PARCOURS_DOCTORAL_EMAIL_STUDENT_COURSE_ENROLLMENT_NEEDS_UPDATE,
    PARCOURS_DOCTORAL_EMAIL_STUDENT_COURSE_ENROLLMENT_REFUSED,
    PARCOURS_DOCTORAL_EMAIL_STUDENT_DOCTORAL_TRAINING_NEEDS_UPDATE,
    PARCOURS_DOCTORAL_EMAIL_STUDENT_DOCTORAL_TRAINING_REFUSED,
)
from parcours_doctoral.mail_templates.signatures import (
    PARCOURS_DOCTORAL_EMAIL_MEMBER_REMOVED,
    PARCOURS_DOCTORAL_EMAIL_SIGNATURE_REFUSAL,
    PARCOURS_DOCTORAL_EMAIL_SIGNATURE_REQUESTS_ACTOR,
    PARCOURS_DOCTORAL_EMAIL_SIGNATURE_REQUESTS_STUDENT,
    PARCOURS_DOCTORAL_EMAIL_SIGNATURE_STUDENT,
)


def remove_templates(apps, _):
    templates_to_delete = [
        PARCOURS_DOCTORAL_EMAIL_CONFIRMATION_PAPER_INFO_STUDENT,
        PARCOURS_DOCTORAL_EMAIL_CONFIRMATION_PAPER_SUBMISSION_ADRE,
        PARCOURS_DOCTORAL_EMAIL_CONFIRMATION_PAPER_ON_SUCCESS_STUDENT,
        PARCOURS_DOCTORAL_EMAIL_CONFIRMATION_PAPER_ON_SUCCESS_ADRE,
        PARCOURS_DOCTORAL_EMAIL_CONFIRMATION_PAPER_ON_SUCCESS_ADRI,
        PARCOURS_DOCTORAL_EMAIL_CONFIRMATION_PAPER_ON_FAILURE_STUDENT,
        PARCOURS_DOCTORAL_EMAIL_CONFIRMATION_PAPER_ON_FAILURE_ADRE,
        PARCOURS_DOCTORAL_EMAIL_CONFIRMATION_PAPER_ON_FAILURE_ADRI,
        PARCOURS_DOCTORAL_EMAIL_CONFIRMATION_PAPER_ON_RETAKING_STUDENT,
        PARCOURS_DOCTORAL_EMAIL_CONFIRMATION_PAPER_ON_RETAKING_ADRE,
        PARCOURS_DOCTORAL_EMAIL_CONFIRMATION_PAPER_ON_RETAKING_ADRI,
        PARCOURS_DOCTORAL_EMAIL_REFERENCE_PROMOTER_DOCTORAL_TRAININGS_SUBMITTED,
        PARCOURS_DOCTORAL_EMAIL_STUDENT_DOCTORAL_TRAINING_NEEDS_UPDATE,
        PARCOURS_DOCTORAL_EMAIL_STUDENT_DOCTORAL_TRAINING_REFUSED,
        PARCOURS_DOCTORAL_EMAIL_REFERENCE_PROMOTER_COMPLEMENTARY_TRAININGS_SUBMITTED,
        PARCOURS_DOCTORAL_EMAIL_STUDENT_COMPLEMENTARY_TRAINING_REFUSED,
        PARCOURS_DOCTORAL_EMAIL_STUDENT_COMPLEMENTARY_TRAINING_NEEDS_UPDATE,
        PARCOURS_DOCTORAL_EMAIL_REFERENCE_PROMOTER_COURSE_ENROLLMENTS_SUBMITTED,
        PARCOURS_DOCTORAL_EMAIL_STUDENT_COURSE_ENROLLMENT_REFUSED,
        PARCOURS_DOCTORAL_EMAIL_STUDENT_COURSE_ENROLLMENT_NEEDS_UPDATE,
        PARCOURS_DOCTORAL_EMAIL_MEMBER_REMOVED,
        PARCOURS_DOCTORAL_EMAIL_SIGNATURE_REQUESTS_STUDENT,
        PARCOURS_DOCTORAL_EMAIL_SIGNATURE_REQUESTS_ACTOR,
        PARCOURS_DOCTORAL_EMAIL_SIGNATURE_STUDENT,
        PARCOURS_DOCTORAL_EMAIL_SIGNATURE_REFUSAL,
        PARCOURS_DOCTORAL_EMAIL_GENERIC,
    ]
    MailTemplate = apps.get_model('osis_mail_template', 'MailTemplate')
    MailTemplate.objects.filter(identifier__in=templates_to_delete).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("parcours_doctoral", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(remove_templates, migrations.RunPython.noop),
        MailTemplateMigration(
            PARCOURS_DOCTORAL_EMAIL_CONFIRMATION_PAPER_SUBMISSION_ADRE,
            {
                'en': '[OSIS] The confirmation form has been submitted by {student_first_name} {student_last_name} '
                '(Financing: {scholarship_grant_acronym})',
                'fr-be': "[OSIS] Le formulaire d'épreuve de confirmation a été soumis par {student_first_name} "
                "{student_last_name} (Financement : {scholarship_grant_acronym})",
            },
            {
                'en': '''<p>Hello,</p>

        <p>
            {student_first_name} {student_last_name} has submitted the confirmation form for the {training_title} 
            (Financing: {scholarship_grant_acronym}).
        </p>

        <p>
            ---<br/>
            The OSIS Team
        </p>
        ''',
                'fr-be': '''<p>Bonjour,</p>

        <p>
            {student_first_name} {student_last_name} a soumis son formulaire de confirmation pour son {training_title} 
            (Financement : {scholarship_grant_acronym}).
        </p>

        <p>
            ---<br/>
            L'équipe OSIS
        </p>
        ''',
            },
        ),
        MailTemplateMigration(
            PARCOURS_DOCTORAL_EMAIL_CONFIRMATION_PAPER_INFO_STUDENT,
            {
                'en': '[OSIS] Information for the organisation of your confirmation paper scheduled on '
                '{confirmation_paper_date}',
                'fr-be': '[OSIS] Informations pour l’organisation de votre épreuve de confirmation prévue le '
                '{confirmation_paper_date}',
            },
            {
                'en': '''<p>Hello {student_first_name} {student_last_name},</p>

                <p>
                    In order to best prepare your confirmation paper, we would like to inform you that you are responsible
                    for:
                </p>

                <ul>
                    <li>Organizing the event,</li>
                    <li>Ensuring the availability of the supervisory panel,</li>
                    <li>Book the room,</li>
                    <li>Sending your research report to the members of the supervisory panel,</li>
                    <li>
                        Uploading your research report to OSIS by clicking 
                        <a href="{confirmation_paper_link_front}">here</a>.
                    </li>
                </ul>

                <p>
                    We also remind you that 20 credits must be obtained before the confirmation paper.
                </p>

                <p>
                    Regards,
                </p>

                <p>
                    ---<br/>
                    The OSIS Team
                </p>
                    ''',
                'fr-be': '''<p>Bonjour,</p>

                <p>
                    Afin de préparer au mieux votre épreuve de confirmation, nous vous précisons que vous êtes chargé :
                </p>

                <ul>
                    <li>De l’organisation de l’épreuve,</li>
                    <li>De vous assurer de la disponibilité du comité d’accompagnement,</li>
                    <li>De réserver la salle,</li>
                    <li>D’envoyer votre rapport de recherche aux membre du comité d’accompagnement,</li>
                    <li>
                        De téléverser votre rapport de recherche dans OSIS en cliquant 
                        <a href="{confirmation_paper_link_front}">ici</a>.
                    </li>
                </ul>

                <p>
                    Nous vous rappelons également que le nombre de crédits à obtenir avant l’épreuve de confirmation est de 
                    20 ECTS.
                </p>

                <p>
                    Bien cordialement,
                </p>

                <p>
                    ---<br/>
                    L'équipe OSIS
                </p>
                    ''',
            },
        ),
        MailTemplateMigration(
            PARCOURS_DOCTORAL_EMAIL_CONFIRMATION_PAPER_ON_SUCCESS_STUDENT,
            {
                'en': '[OSIS] Success of your confirmation paper',
                'fr-be': '[OSIS] Réussite de votre épreuve de confirmation',
            },
            {
                'en': '''<p>Hello {student_first_name} {student_last_name},</p>

        <p>
            We would like to inform you that you have passed your confirmation paper taken on {confirmation_paper_date} 
            for your {training_title}.
        </p>

        <p>
            Your certificate of achievement is available <a href="{confirmation_paper_link_front}">here</a>.
        </p>

        <p>
            ---<br/>
            The OSIS Team
        </p>
            ''',
                'fr-be': '''<p>Bonjour {student_first_name} {student_last_name},</p>

        <p>
            Nous tenons à vous informer que vous avez réussi votre épreuve de confirmation passée le 
            {confirmation_paper_date} pour votre {training_title}.
        </p>

        <p>
            Votre certificat de réussite est disponible <a href="{confirmation_paper_link_front}">ici</a>.
        </p>

        <p>
            ---<br/>
            L'équipe OSIS
        </p>
            ''',
            },
        ),
        MailTemplateMigration(
            PARCOURS_DOCTORAL_EMAIL_CONFIRMATION_PAPER_ON_SUCCESS_ADRE,
            {
                'en': '[OSIS] Success of the confirmation paper of {student_first_name} {student_last_name} '
                '(Financing: {scholarship_grant_acronym}) - {training_title}',
                'fr-be': "[OSIS] Réussite de l'épreuve de confirmation de {student_first_name} "
                "{student_last_name} (Financement : {scholarship_grant_acronym}) - {training_title}",
            },
            {
                'en': '''<p>Hello,</p>

    <p>
        {student_first_name} {student_last_name} has passed the confirmation paper on {confirmation_paper_date} 
        for the {training_title} (Financing: {scholarship_grant_acronym}).
    </p>

    <p>
        ---<br/>
        The OSIS Team
    </p>
        ''',
                'fr-be': '''<p>Bonjour,</p>

    <p>
        {student_first_name} {student_last_name} a réussi son épreuve de confirmation le {confirmation_paper_date} 
        pour son {training_title} (Financement : {scholarship_grant_acronym}).
    </p>

    <p>
        ---<br/>
        L'équipe OSIS
    </p>
        ''',
            },
        ),
        MailTemplateMigration(
            PARCOURS_DOCTORAL_EMAIL_CONFIRMATION_PAPER_ON_SUCCESS_ADRI,
            {
                'en': '[OSIS] Success of the confirmation paper of {student_first_name} {student_last_name} '
                '(Financing: {scholarship_grant_acronym}) - {training_title}',
                'fr-be': "[OSIS] Réussite de l'épreuve de confirmation de {student_first_name} "
                "{student_last_name} (Financement : {scholarship_grant_acronym}) - {training_title}",
            },
            {
                'en': '''<p>Hello,</p>

    <p>
        {student_first_name} {student_last_name} has passed the confirmation paper on {confirmation_paper_date} 
        for the {training_title} (Financing: {scholarship_grant_acronym}).
    </p>

    <p>
        ---<br/>
        The OSIS Team
    </p>
        ''',
                'fr-be': '''<p>Bonjour,</p>

    <p>
        {student_first_name} {student_last_name} a réussi son épreuve de confirmation le {confirmation_paper_date} 
        pour son {training_title} (Financement : {scholarship_grant_acronym}).
    </p>

    <p>
        ---<br/>
        L'équipe OSIS
    </p>
                    ''',
            },
        ),
        MailTemplateMigration(
            PARCOURS_DOCTORAL_EMAIL_CONFIRMATION_PAPER_ON_FAILURE_STUDENT,
            {
                'en': '[OSIS] Failure of your confirmation paper',
                'fr-be': '[OSIS] Échec à votre épreuve de confirmation',
            },
            {
                'en': '''<p>Hello {student_first_name} {student_last_name},</p>

    <p>
        We would like to inform you that you have failed your confirmation paper taken on {confirmation_paper_date} 
        for your {training_title}.
    </p>

    <p>
        ---<br/>
        The OSIS Team
    </p>
        ''',
                'fr-be': '''<p>Bonjour {student_first_name} {student_last_name},</p>

    <p>
        Nous tenons à vous informer que vous avez échoué à votre épreuve de confirmation passée le 
        {confirmation_paper_date} pour votre {training_title}.
    </p>

    <p>
        ---<br/>
        L'équipe OSIS
    </p>
        ''',
            },
        ),
        MailTemplateMigration(
            PARCOURS_DOCTORAL_EMAIL_CONFIRMATION_PAPER_ON_FAILURE_ADRE,
            {
                'en': '[OSIS] Failure of the confirmation paper of {student_first_name} {student_last_name} '
                '(Financing: {scholarship_grant_acronym}) - {training_title}',
                'fr-be': "[OSIS] Échec de l'épreuve de confirmation de {student_first_name} "
                "{student_last_name} (Financement : {scholarship_grant_acronym}) - {training_title}",
            },
            {
                'en': '''<p>Hello,</p>

    <p>
        {student_first_name} {student_last_name} has failed the confirmation paper on {confirmation_paper_date} 
        for the {training_title} (Financing: {scholarship_grant_acronym}).
    </p>

    <p>
        ---<br/>
        The OSIS Team
    </p>
        ''',
                'fr-be': '''<p>Bonjour,</p>

    <p>
        {student_first_name} {student_last_name} a échoué à son épreuve de confirmation le {confirmation_paper_date} 
        pour son {training_title} (Financement : {scholarship_grant_acronym}).
    </p>

    <p>
        ---<br/>
        L'équipe OSIS
    </p>
        ''',
            },
        ),
        MailTemplateMigration(
            PARCOURS_DOCTORAL_EMAIL_CONFIRMATION_PAPER_ON_FAILURE_ADRI,
            {
                'en': '[OSIS] Failure of the confirmation paper of {student_first_name} {student_last_name} '
                '(Financing: {scholarship_grant_acronym}) - {training_title}',
                'fr-be': "[OSIS] Échec de l'épreuve de confirmation de {student_first_name} "
                "{student_last_name} (Financement : {scholarship_grant_acronym}) - {training_title}",
            },
            {
                'en': '''<p>Hello,</p>

    <p>
        {student_first_name} {student_last_name} has failed the confirmation paper on {confirmation_paper_date} 
        for the {training_title} (Financing: {scholarship_grant_acronym}).
    </p>

    <p>
        ---<br/>
        The OSIS Team
    </p>
        ''',
                'fr-be': '''<p>Bonjour,</p>

    <p>
        {student_first_name} {student_last_name} a échoué à son épreuve de confirmation le {confirmation_paper_date} 
        pour son {training_title} (Financement : {scholarship_grant_acronym}).
    </p>

    <p>
        ---<br/>
        L'équipe OSIS
    </p>
                    ''',
            },
        ),
        MailTemplateMigration(
            PARCOURS_DOCTORAL_EMAIL_CONFIRMATION_PAPER_ON_RETAKING_STUDENT,
            {
                'en': '[OSIS] Need to retake your confirmation test',
                'fr-be': '[OSIS] Nécessité de repasser votre épreuve de confirmation',
            },
            {
                'en': '''<p>Hello {student_first_name} {student_last_name},</p>

    <p>
        As a result of your confirmation paper, taken on {confirmation_paper_date} for your {training_title}, 
        the supervisory panel has decided that it is necessary for you to retake it.
    </p>

    <p>
        ---<br/>
        The OSIS Team
    </p>
        ''',
                'fr-be': '''<p>Bonjour {student_first_name} {student_last_name},</p>

    <p>
        Nous tenons à vous informer que suite à votre épreuve de confirmation du {confirmation_paper_date} pour votre 
        {training_title}, le comité d’accompagnement a acté qu’il est nécessaire que vous repassiez à nouveau votre 
        épreuve de confirmation.
    </p>

    <p>
        ---<br/>
        L'équipe OSIS
    </p>
        ''',
            },
        ),
        MailTemplateMigration(
            PARCOURS_DOCTORAL_EMAIL_CONFIRMATION_PAPER_ON_RETAKING_ADRE,
            {
                'en': "[OSIS] {student_first_name} {student_last_name} must retake the confirmation paper "
                "(Financing: {scholarship_grant_acronym}) - {training_title})",
                'fr-be': "[OSIS] {student_first_name} {student_last_name} doit repasser son épreuve de confirmation "
                "(Financement : {scholarship_grant_acronym}) - {training_title})",
            },
            {
                'en': '''<p>Hello,</p>

    <p>
        As a result of the confirmation paper of {student_first_name} {student_last_name}, taken on 
        {confirmation_paper_date} for the {training_title} (Funding: {scholarship_grant_acronym}), the supervisory panel 
        has decided that it is necessary for the doctoral student to retake it.
    </p>

    <p>
        ---<br/>
        The OSIS Team
    </p>
        ''',
                'fr-be': '''<p>Bonjour,</p>

    <p>
        Suite à l’épreuve de confirmation de {student_first_name} {student_last_name}, réalisée le 
        {confirmation_paper_date} pour son {training_title} (Financement : {scholarship_grant_acronym}), le comité 
        d’accompagnement a acté qu’il était nécessaire que le doctorand repasse son épreuve de confirmation.
    </p>

    <p>
        ---<br/>
        L'équipe OSIS
    </p>
        ''',
            },
        ),
        MailTemplateMigration(
            PARCOURS_DOCTORAL_EMAIL_CONFIRMATION_PAPER_ON_RETAKING_ADRI,
            {
                'en': "[OSIS] {student_first_name} {student_last_name} must retake the confirmation paper "
                "(Financing: {scholarship_grant_acronym}) - {training_title})",
                'fr-be': "[OSIS] {student_first_name} {student_last_name} doit repasser son épreuve de confirmation "
                "(Financement : {scholarship_grant_acronym}) - {training_title})",
            },
            {
                'en': '''<p>Hello,</p>

    <p>
        As a result of the confirmation paper of {student_first_name} {student_last_name}, taken on 
        {confirmation_paper_date} for the {training_title} (Funding: {scholarship_grant_acronym}), the supervisory panel 
        has decided that it is necessary for the doctoral student to retake it.
    </p>

    <p>
        ---<br/>
        The OSIS Team
    </p>
        ''',
                'fr-be': '''<p>Bonjour,</p>

    <p>
        Suite à l’épreuve de confirmation de {student_first_name} {student_last_name}, réalisée le 
        {confirmation_paper_date} pour son {training_title} (Financement : {scholarship_grant_acronym}), le comité 
        d’accompagnement a acté qu’il était nécessaire que le doctorand repasse son épreuve de confirmation.
    </p>

    <p>
        ---<br/>
        L'équipe OSIS
    </p>
        ''',
            },
        ),
        MailTemplateMigration(
            PARCOURS_DOCTORAL_EMAIL_REFERENCE_PROMOTER_DOCTORAL_TRAININGS_SUBMITTED,
            {
                'en': '[OSIS] New doctoral training activities been submitted by {student_first_name} {student_last_name}',
                'fr-be': "[OSIS] De nouvelles activités de formation doctorale ont été soumises par "
                "{student_first_name} {student_last_name}",
            },
            {
                'en': '''<p>Hello,</p>

        <p>
            {student_first_name} {student_last_name} have submitted new doctoral training activities for {training_title}, 
            you can review them by following this link: {parcours_doctoral_link_front_doctoral_training}.
        </p>

        <p>
            ---<br/>
            The OSIS Team
        </p>
        ''',
                'fr-be': '''<p>Bonjour,</p>

        <p>
            {student_first_name} {student_last_name} a soumis de nouvelles activités de formation doctorale 
            pour son {training_title}, vous pouvez les consulter en suivant ce lien : {parcours_doctoral_link_front_doctoral_training}.
        </p>

        <p>
            ---<br/>
            L'équipe OSIS
        </p>
        ''',
            },
        ),
        MailTemplateMigration(
            PARCOURS_DOCTORAL_EMAIL_STUDENT_DOCTORAL_TRAINING_REFUSED,
            {
                'en': '[OSIS] A doctoral training activity has been refused',
                'fr-be': "[OSIS] Une activité de formation doctorale a été refusée",
            },
            {
                'en': '''<p>Hello,</p>

        <p>
            The submitted doctoral training activity entitled <em>{activity_title}</em> for your {training_title} has been refused, 
            you can review all activities by following this link: {parcours_doctoral_link_front_doctoral_training}.

            Here's the reason for this refusal: {reason}
        </p>

        <p>
            ---<br/>
            The OSIS Team
        </p>
        ''',
                'fr-be': '''<p>Bonjour,</p>

        <p>
            L'activité de formation doctorale soumise intitulée <em>{activity_title}</em> pour votre {training_title} a été refusée,
            vous pouvez la consulter en suivant ce lien : {parcours_doctoral_link_front_doctoral_training}.

            La raison invoquée pour ce refus : {reason}
        </p>

        <p>
            ---<br/>
            L'équipe OSIS
        </p>
        ''',
            },
        ),
        MailTemplateMigration(
            PARCOURS_DOCTORAL_EMAIL_STUDENT_DOCTORAL_TRAINING_NEEDS_UPDATE,
            {
                'en': '[OSIS] A doctoral training activity needs to be updated',
                'fr-be': "[OSIS] Une activité de formation doctorale doit être mise à jour",
            },
            {
                'en': '''<p>Hello,</p>

        <p>
            The submitted doctoral training activity entitled <em>{activity_title}</em> for {training_title} must be updated, 
            you can review all activities by following this link: {parcours_doctoral_link_front_doctoral_training}.

            Here's why it needs to be updated: {reason}
        </p>

        <p>
            ---<br/>
            The OSIS Team
        </p>
        ''',
                'fr-be': '''<p>Bonjour,</p>

        <p>
            L'activité de formation doctorale soumise intitulée <em>{activity_title}</em> doit être mise à jour 
            pour {training_title}, vous pouvez la consulter en suivant ce lien : {parcours_doctoral_link_front_doctoral_training}.

            Voici ce pourquoi vous devez la modifier : {reason}
        </p>

        <p>
            ---<br/>
            L'équipe OSIS
        </p>
        ''',
            },
        ),
        MailTemplateMigration(
            PARCOURS_DOCTORAL_EMAIL_REFERENCE_PROMOTER_COMPLEMENTARY_TRAININGS_SUBMITTED,
            {
                'en': '[OSIS] New complementary training activities been submitted by '
                '{student_first_name} {student_last_name}',
                'fr-be': "[OSIS] De nouvelles activités de formation complémentaire ont été soumises par {student_first_name} "
                "{student_last_name}",
            },
            {
                'en': '''<p>Hello,</p>

        <p>
            {student_first_name} {student_last_name} have submitted new complementary training activities for {training_title}, 
            you can review them by following this link: {parcours_doctoral_link_front_complementary_training}.
        </p>

        <p>
            ---<br/>
            The OSIS Team
        </p>
        ''',
                'fr-be': '''<p>Bonjour,</p>

        <p>
            {student_first_name} {student_last_name} a soumis de nouvelles activités de formation complémentaire pour son {training_title},
            vous pouvez les consulter en suivant ce lien : {parcours_doctoral_link_front_complementary_training}.
        </p>

        <p>
            ---<br/>
            L'équipe OSIS
        </p>
        ''',
            },
        ),
        MailTemplateMigration(
            PARCOURS_DOCTORAL_EMAIL_STUDENT_COMPLEMENTARY_TRAINING_REFUSED,
            {
                'en': '[OSIS] A complementary training activity has been refused',
                'fr-be': "[OSIS] Une activité de formation complémentaire a été refusée",
            },
            {
                'en': '''<p>Hello,</p>

        <p>
            The submitted complementary training activity entitled <em>{activity_title}</em> for your {training_title} has been refused, 
            you can review all activities by following this link: {parcours_doctoral_link_front_complementary_training}.

            Here's the reason for this refusal: {reason}
        </p>

        <p>
            ---<br/>
            The OSIS Team
        </p>
        ''',
                'fr-be': '''<p>Bonjour,</p>

        <p>
            L'activité de formation complémentaire soumise intitulée <em>{activity_title}</em> pour votre {training_title} a été refusée,
            vous pouvez la consulter en suivant ce lien : {parcours_doctoral_link_front_complementary_training}.

            La raison invoquée pour ce refus : {reason}
        </p>

        <p>
            ---<br/>
            L'équipe OSIS
        </p>
        ''',
            },
        ),
        MailTemplateMigration(
            PARCOURS_DOCTORAL_EMAIL_STUDENT_COMPLEMENTARY_TRAINING_NEEDS_UPDATE,
            {
                'en': '[OSIS] A complementary training activity needs to be updated',
                'fr-be': "[OSIS] Une activité de formation complémentaire doit être mise à jour",
            },
            {
                'en': '''<p>Hello,</p>

        <p>
            The submitted complementary training activity entitled <em>{activity_title}</em> for {training_title} must be updated, 
            you can review them by following this link: {parcours_doctoral_link_front_complementary_training}.

            Here's why it needs to be updated: {reason}
        </p>

        <p>
            ---<br/>
            The OSIS Team
        </p>
        ''',
                'fr-be': '''<p>Bonjour,</p>

        <p>
            L'activité de formation complémentaire soumise intitulée <em>{activity_title}</em> doit être mise à jour pour {training_title},
            vous pouvez la consulter en suivant ce lien : {parcours_doctoral_link_front_complementary_training}.

            Voici ce pourquoi vous devez la modifier : {reason}
        </p>

        <p>
            ---<br/>
            L'équipe OSIS
        </p>
        ''',
            },
        ),
        MailTemplateMigration(
            PARCOURS_DOCTORAL_EMAIL_REFERENCE_PROMOTER_COURSE_ENROLLMENTS_SUBMITTED,
            {
                'en': '[OSIS] New course enrollments been submitted by {student_first_name} {student_last_name}',
                'fr-be': "[OSIS] Nouvelles inscriptions aux cours soumises par {student_first_name} "
                "{student_last_name}",
            },
            {
                'en': '''<p>Hello,</p>

        <p>
            {student_first_name} {student_last_name} have submitted new course enrollments for {training_title}, 
            you can review them by following this link: {parcours_doctoral_link_front_course_enrollment}.
        </p>

        <p>
            ---<br/>
            The OSIS Team
        </p>
        ''',
                'fr-be': '''<p>Bonjour,</p>

        <p>
            {student_first_name} {student_last_name} a soumis de nouvelles inscriptions aux cours pour son {training_title},
            vous pouvez les consulter en suivant ce lien : {parcours_doctoral_link_front_course_enrollment}.
        </p>

        <p>
            ---<br/>
            L'équipe OSIS
        </p>
        ''',
            },
        ),
        MailTemplateMigration(
            PARCOURS_DOCTORAL_EMAIL_STUDENT_COURSE_ENROLLMENT_REFUSED,
            {
                'en': '[OSIS] A course enrollment has been refused',
                'fr-be': "[OSIS] Une inscription à un cours a été refusée",
            },
            {
                'en': '''<p>Hello,</p>

        <p>
            The submitted course enrollment entitled <em>{activity_title}</em> for your {training_title} has been refused, 
            you can review all courses by following this link: {parcours_doctoral_link_front_course_enrollment}.

            Here's the reason for this refusal: {reason}
        </p>

        <p>
            ---<br/>
            The OSIS Team
        </p>
        ''',
                'fr-be': '''<p>Bonjour,</p>

        <p>
            Une inscription à un cours intitulé <em>{activity_title}</em> pour votre {training_title} a été refusée,
            vous pouvez la consulter en suivant ce lien : {parcours_doctoral_link_front_course_enrollment}.

            La raison invoquée pour ce refus : {reason}
        </p>

        <p>
            ---<br/>
            L'équipe OSIS
        </p>
        ''',
            },
        ),
        MailTemplateMigration(
            PARCOURS_DOCTORAL_EMAIL_STUDENT_COURSE_ENROLLMENT_NEEDS_UPDATE,
            {
                'en': '[OSIS] A course enrollment needs to be updated',
                'fr-be': "[OSIS] Une inscription à un cours doit être mise à jour",
            },
            {
                'en': '''<p>Hello,</p>

        <p>
            The submitted course enrollment entitled <em>{activity_title}</em> for {training_title} must be updated, 
            you can review all courses by following this link: {parcours_doctoral_link_front_course_enrollment}.

            Here's why it needs to be updated: {reason}
        </p>

        <p>
            ---<br/>
            The OSIS Team
        </p>
        ''',
                'fr-be': '''<p>Bonjour,</p>

        <p>
            Une inscription à un cours intitulé <em>{activity_title}</em> doit être mise à jour pour {training_title},
            vous pouvez la consulter en suivant ce lien : {parcours_doctoral_link_front_course_enrollment}.

            Voici ce pourquoi vous devez la modifier : {reason}
        </p>

        <p>
            ---<br/>
            L'équipe OSIS
        </p>
        ''',
            },
        ),
        MailTemplateMigration(
            PARCOURS_DOCTORAL_EMAIL_MEMBER_REMOVED,
            {
                'en': '[OSIS] Removal from supervision group by {student_first_name} {student_last_name}',
                'fr-be': "[OSIS] Retrait du groupe de supervision par {student_first_name} {student_last_name}",
            },
            {
                'en': '''<p>Hello {actor_first_name} {actor_last_name},</p>

    <p>{student_first_name} {student_last_name} has removed you from 
    the supervision group concerning {training_title}.</p>

    <p>---<br/>
    The OSIS Team</p>
    ''',
                'fr-be': '''<p>Bonjour {actor_first_name} {actor_last_name},</p>

    <p>{student_first_name} {student_last_name} vous a retiré du groupe de supervision 
    concernant son {training_title}.</p>

    <p>---<br/>
    L'équipe OSIS</p>
    ''',
            },
        ),
        MailTemplateMigration(
            PARCOURS_DOCTORAL_EMAIL_SIGNATURE_REQUESTS_STUDENT,
            {
                'en': '[OSIS] Signature requests sent successfully',
                'fr-be': '[OSIS] Demande de signature envoyées avec succès',
            },
            {
                'en': '''<p>Hello {student_first_name} {student_last_name},</p>

    <p>Requests for signatures concerning your application to {training_title} have been sent.</p>

    <ul>
    <li>{actors_as_list_items}</li> 

    <p>You will be notified for any action on their part (acceptance or refusal), you can also transfer a document 
    attesting their approval for each of them.</p>

    <p>---<br/>
    The OSIS Team</p>
    ''',
                'fr-be': '''<p>Bonjour {student_first_name} {student_last_name},</p>

    <p>Les demandes de signatures concernant votre demande d'parcours doctoral en {training_title} ont bien été envoyées.</p>

    <ul>
    <li>{actors_as_list_items}</li>
    </ul>

    <p>Vous serez notifiés pour toute action de leur part (acceptation ou refus), vous pouvez également transférer
    un document attestant leur approbation pour chacun d'eux.

    <p>---<br/>
    L'équipe OSIS</p>
    ''',
            },
        ),
        MailTemplateMigration(
            PARCOURS_DOCTORAL_EMAIL_SIGNATURE_REQUESTS_ACTOR,
            {
                'en': '[OSIS] Invite to supervise {student_first_name} {student_last_name} for {training_title}',
                'fr-be': '[OSIS] Invitation à superviser {student_first_name} {student_last_name} '
                'pour un {training_title}',
            },
            {
                'en': '''<p>Hello {signataire_first_name} {signataire_last_name},</p>

    <p>{student_first_name} {student_last_name} has added you as {signataire_role} for {training_title}.</p>

    <p>Please indicate your approval or refusal and view the parcours doctoral request by clicking 
    on the {parcours_doctoral_link_front} link.</p>

    <p>---<br/>
    The OSIS Team</p>
    ''',
                'fr-be': '''<p>Bonjour {signataire_first_name} {signataire_last_name},</p>

    <p>{student_first_name} {student_last_name} vous a ajouté en tant que {signataire_role} 
    pour son {training_title}.</p>

    <p>Merci d'indiquer votre approbation ou refus et visualiser sa demande en cliquer sur le lien {parcours_doctoral_link_front}.

    <p>---<br/>
    L'équipe OSIS</p>
    ''',
            },
        ),
        MailTemplateMigration(
            PARCOURS_DOCTORAL_EMAIL_SIGNATURE_STUDENT,
            {
                'en': '[OSIS] Answer from {signataire_first_name} {signataire_last_name} for {training_title}',
                'fr-be': '[OSIS] Réponse de {signataire_first_name} {signataire_last_name} pour un {training_title}',
            },
            {
                'en': '''<p>Hello {student_first_name} {student_last_name},</p>

    <p>{signataire_first_name} {signataire_last_name} ({signataire_role}) has answered your request for {training_title} 
    with the following : {decision}.</p>

    <p>---<br/>
    The OSIS Team</p>
    ''',
                'fr-be': '''<p>Bonjour {student_first_name} {student_last_name},</p>

    <p>{signataire_first_name} {signataire_last_name} ({signataire_role}) a répondu à votre demande de {training_title} 
    avec ce qui suit : {decision}.</p>

    <p>---<br/>
    L'équipe OSIS</p>
    ''',
            },
        ),
        MailTemplateMigration(
            PARCOURS_DOCTORAL_EMAIL_SIGNATURE_REFUSAL,
            {
                'en': "[OSIS] Refusal from a member of the supervision group for the {training_title} "
                "of {student_first_name} {student_last_name}",
                'fr-be': "[OSIS] Refus d'un membre du groupe de supervision pour le {training_title} "
                "de {student_first_name} {student_last_name}",
            },
            {
                'en': '''<p>Hello {actor_first_name} {actor_last_name},</p>

    <p>{signataire_first_name} {signataire_last_name} has refused being a member of the supervision group 
    for {student_first_name} {student_last_name} ({training_title}) with the following reason: {reason}.</p>

    <p>Your decision is now on hold and you may be requested again once the student has made some changes.</p>

    <p>---<br/>
    The OSIS Team</p>
    ''',
                'fr-be': '''<p>Bonjour {actor_first_name} {actor_last_name},</p>

    <p>{signataire_first_name} {signataire_last_name} a refusé de faire partie du groupe de supervision 
    pour {student_first_name} {student_last_name} ({training_title}) avec la raison suivante : {reason}.</p>

    <p>Votre décision est maintenant en suspens et vous pourriez être sollicité à nouveau une fois que le candidat 
    aura modifié le groupe de supervision.</p>

    <p>---<br/>
    L'équipe OSIS</p>
    ''',
            },
        ),
        MailTemplateMigration(
            PARCOURS_DOCTORAL_EMAIL_GENERIC,
            {
                'en': "Information about your {training_title} doctoral training",
                'fr-be': "Informations sur votre parcours doctoral {training_title}",
            },
            {
                'en': '''<p>Hello {student_first_name} {student_last_name},</p>

    <p>Here are some information about you doctoral training in {training_title}.</p>

    <p>---<br/>
    The OSIS Team</p>''',
                'fr-be': '''<p>Bonjour {student_first_name} {student_last_name},</p>

    <p>Voici quelques informations à propos de votre parcours doctoral en {training_title}.</p>

    <p>---<br/>
    L'équipe OSIS</p>''',
            },
        ),
    ]
