# Generated by Django 4.2.16 on 2024-11-07 15:56

from django.db import migrations, models
import django.db.models.deletion
import osis_document.contrib.fields


class Migration(migrations.Migration):

    dependencies = [
        ("osis_signature", "0003_external_actor"),
        ("parcours_doctoral", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ParcoursDoctoralSupervisionActor",
            fields=[
                (
                    "actor_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="osis_signature.actor",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("PROMOTER", "Supervisor"),
                            ("CA_MEMBER", "CA Member"),
                        ],
                        max_length=50,
                    ),
                ),
                ("is_doctor", models.BooleanField(default=False)),
                (
                    "internal_comment",
                    models.TextField(
                        blank=True, default="", verbose_name="Internal comment"
                    ),
                ),
                (
                    "pdf_from_candidate",
                    osis_document.contrib.fields.FileField(
                        base_field=models.UUIDField(),
                        default=list,
                        size=1,
                        verbose_name="PDF file",
                    ),
                ),
                ("is_reference_promoter", models.BooleanField(default=False)),
            ],
            bases=("osis_signature.actor",),
        ),
        migrations.AlterField(
            model_name="jurymember",
            name="promoter",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"type": "PROMOTER"},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="parcours_doctoral.parcoursdoctoralsupervisionactor",
                verbose_name="Supervisor",
            ),
        ),
    ]
