# Generated by Django 3.2.25 on 2024-10-31 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0706_auto_20241024_0818'),
        ('parcours_doctoral', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcoursdoctoral',
            name='training',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='base.educationgroupyear', verbose_name='Course'),
            preserve_default=False,
        ),
    ]
