# Generated by Django 3.2.25 on 2024-11-06 11:11

from django.db import migrations, models
import django.db.models.deletion
import osis_document.contrib.fields
import osis_signature.contrib.fields


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0233_parcours_doctoral_refactoring'),
        ('reference', '0018_country_active'),
        ('osis_signature', '0003_external_actor'),
        ('base', '0706_auto_20241024_0818'),
        ('parcours_doctoral', '0002_parcoursdoctoral_training'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parcoursdoctoral',
            old_name='candidate',
            new_name='student',
        ),
        migrations.AddField(
            model_name='parcoursdoctoral',
            name='additional_training_project',
            field=osis_document.contrib.fields.FileField(base_field=models.UUIDField(), default=list, size=None, verbose_name='Complementary training proposition'),
        ),
        migrations.AddField(
            model_name='parcoursdoctoral',
            name='admission',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='admission.doctorateadmission', verbose_name='Admission'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parcoursdoctoral',
            name='cotutelle',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parcoursdoctoral',
            name='cotutelle_convention',
            field=osis_document.contrib.fields.FileField(base_field=models.UUIDField(), default=list, size=1, verbose_name='Joint supervision agreement'),
        ),
        migrations.AddField(
            model_name='parcoursdoctoral',
            name='cotutelle_institution',
            field=models.UUIDField(blank=True, default=None, null=True, verbose_name='Institution'),
        ),
        migrations.AddField(
            model_name='parcoursdoctoral',
            name='cotutelle_institution_fwb',
            field=models.BooleanField(blank=True, null=True, verbose_name='Institution Federation Wallonie-Bruxelles'),
        ),
        migrations.AddField(
            model_name='parcoursdoctoral',
            name='cotutelle_motivation',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Motivation'),
        ),
        migrations.AddField(
            model_name='parcoursdoctoral',
            name='cotutelle_opening_request',
            field=osis_document.contrib.fields.FileField(base_field=models.UUIDField(), default=list, size=1, verbose_name='Cotutelle request document'),
        ),
        migrations.AddField(
            model_name='parcoursdoctoral',
            name='cotutelle_other_documents',
            field=osis_document.contrib.fields.FileField(base_field=models.UUIDField(), default=list, size=None, verbose_name='Other cotutelle-related documents'),
        ),
        migrations.AddField(
            model_name='parcoursdoctoral',
            name='cotutelle_other_institution_address',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Other institution address'),
        ),
        migrations.AddField(
            model_name='parcoursdoctoral',
            name='cotutelle_other_institution_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Other institution name'),
        ),
        migrations.AddField(
            model_name='parcoursdoctoral',
            name='financing_type',
            field=models.CharField(blank=True, choices=[('WORK_CONTRACT', 'WORK_CONTRACT'), ('SEARCH_SCHOLARSHIP', 'SEARCH_SCHOLARSHIP'), ('SELF_FUNDING', 'SELF_FUNDING')], default='', max_length=255, verbose_name='Funding type'),
        ),
        migrations.AddField(
            model_name='parcoursdoctoral',
            name='gantt_graph',
            field=osis_document.contrib.fields.FileField(base_field=models.UUIDField(), default=list, size=None, verbose_name='Gantt chart'),
        ),
        migrations.AddField(
            model_name='parcoursdoctoral',
            name='international_scholarship',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='admission.scholarship', verbose_name='International scholarship'),
        ),
        migrations.AddField(
            model_name='parcoursdoctoral',
            name='other_international_scholarship',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Other international scholarship'),
        ),
        migrations.AddField(
            model_name='parcoursdoctoral',
            name='phd_alread_started',
            field=models.BooleanField(blank=True, null=True, verbose_name='Has your PhD project already started?'),
        ),
        migrations.AddField(
            model_name='parcoursdoctoral',
            name='phd_alread_started_institute',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Institution'),
        ),
        migrations.AddField(
            model_name='parcoursdoctoral',
            name='phd_already_done',
            field=models.CharField(blank=True, choices=[('YES', 'YES'), ('NO', 'NO'), ('PARTIAL', 'PARTIAL')], default='NO', max_length=255, verbose_name='PhD already done'),
        ),
        migrations.AddField(
            model_name='parcoursdoctoral',
            name='phd_already_done_defense_date',
            field=models.DateField(blank=True, null=True, verbose_name='Defense'),
        ),
        migrations.AddField(
            model_name='parcoursdoctoral',
            name='phd_already_done_institution',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Institution'),
        ),
        migrations.AddField(
            model_name='parcoursdoctoral',
            name='phd_already_done_no_defense_reason',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='No defense reason'),
        ),
        migrations.AddField(
            model_name='parcoursdoctoral',
            name='phd_already_done_thesis_domain',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Thesis field'),
        ),
        migrations.AddField(
            model_name='parcoursdoctoral',
            name='program_proposition',
            field=osis_document.contrib.fields.FileField(base_field=models.UUIDField(), default=list, size=None, verbose_name='Program proposition'),
        ),
        migrations.AddField(
            model_name='parcoursdoctoral',
            name='project_abstract',
            field=models.TextField(blank=True, default='', verbose_name='Abstract'),
        ),
        migrations.AddField(
            model_name='parcoursdoctoral',
            name='project_document',
            field=osis_document.contrib.fields.FileField(base_field=models.UUIDField(), default=list, size=None, verbose_name='Project'),
        ),
        migrations.AddField(
            model_name='parcoursdoctoral',
            name='project_title',
            field=models.CharField(blank=True, default='', max_length=1023, verbose_name='Project title'),
        ),
        migrations.AddField(
            model_name='parcoursdoctoral',
            name='recommendation_letters',
            field=osis_document.contrib.fields.FileField(base_field=models.UUIDField(), default=list, size=None, verbose_name='Letters of recommendation'),
        ),
        migrations.AddField(
            model_name='parcoursdoctoral',
            name='supervision_group',
            field=osis_signature.contrib.fields.SignatureProcessField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='osis_signature.process'),
        ),
        migrations.AddField(
            model_name='parcoursdoctoral',
            name='thesis_institute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='base.entityversion', verbose_name='Thesis institute'),
        ),
        migrations.AddField(
            model_name='parcoursdoctoral',
            name='thesis_language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='reference.language', verbose_name='Thesis language'),
        ),
        migrations.AddField(
            model_name='parcoursdoctoral',
            name='thesis_location',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Thesis location'),
        ),
        migrations.AddField(
            model_name='parcoursdoctoral',
            name='work_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Work start date'),
        ),
    ]
