# Generated by Django 4.2.16 on 2024-12-05 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parcours_doctoral", "0002_mail_templates"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parcoursdoctoral",
            name="status",
            field=models.CharField(
                choices=[
                    ("EN_ATTENTE_INJECTION_EPC", "EN_ATTENTE_INJECTION_EPC"),
                    ("EN_COURS_DE_CREATION_PAR_GESTIONNAIRE", "EN_COURS_DE_CREATION_PAR_GESTIONNAIRE"),
                    ("ADMIS", "ADMIS"),
                    ("EN_ATTENTE_DE_SIGNATURE", "EN_ATTENTE_DE_SIGNATURE"),
                    ("CONFIRMATION_SOUMISE", "CONFIRMATION_SOUMISE"),
                    ("CONFIRMATION_REUSSIE", "CONFIRMATION_REUSSIE"),
                    ("NON_AUTORISE_A_POURSUIVRE", "NON_AUTORISE_A_POURSUIVRE"),
                    ("CONFIRMATION_A_REPRESENTER", "CONFIRMATION_A_REPRESENTER"),
                    ("JURY_SOUMIS", "JURY_SOUMIS"),
                    ("JURY_APPROUVE_CA", "JURY_APPROUVE_CA"),
                    ("JURY_APPROUVE_CDD", "JURY_APPROUVE_CDD"),
                    ("JURY_REFUSE_CDD", "JURY_REFUSE_CDD"),
                    ("JURY_APPROUVE_ADRE", "JURY_APPROUVE_ADRE"),
                    ("JURY_REFUSE_ADRE", "JURY_REFUSE_ADRE"),
                ],
                max_length=64,
                verbose_name="Status",
            ),
        ),
    ]
