# Generated by Django 4.2.16 on 2025-01-07 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reference", "0019_scholarship"),
        ("parcours_doctoral", "0002_mail_templates"),
    ]

    operations = [
        migrations.AddField(
            model_name="parcoursdoctoral",
            name="international_scholarship",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="reference.scholarship",
                verbose_name="International scholarship",
            ),
        ),
    ]
