# Generated by Django 4.2.16 on 2024-11-13 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0707_django_4_migration"),
        ("parcours_doctoral", "0003_promoter_doctoratereader_committeemember"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parcoursdoctoral",
            name="status",
            field=models.CharField(
                choices=[
                    ("ADMITTED", "ADMITTED"),
                    ("SUBMITTED_CONFIRMATION", "SUBMITTED_CONFIRMATION"),
                    ("PASSED_CONFIRMATION", "PASSED_CONFIRMATION"),
                    ("NOT_ALLOWED_TO_CONTINUE", "NOT_ALLOWED_TO_CONTINUE"),
                    ("CONFIRMATION_TO_BE_REPEATED", "CONFIRMATION_TO_BE_REPEATED"),
                    ("JURY_SOUMIS", "JURY_SOUMIS"),
                    ("JURY_APPROUVE_CA", "JURY_APPROUVE_CA"),
                    ("JURY_APPROUVE_CDD", "JURY_APPROUVE_CDD"),
                    ("JURY_REFUSE_CDD", "JURY_REFUSE_CDD"),
                    ("JURY_APPROUVE_ADRE", "JURY_APPROUVE_ADRE"),
                    ("JURY_REFUSE_ADRE", "JURY_REFUSE_ADRE"),
                ],
                default="ADMITTED",
                max_length=30,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="parcoursdoctoral",
            name="student",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)ss",
                to="base.person",
                verbose_name="Student",
            ),
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("visible", models.BooleanField(default=True)),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="base.person",
                    ),
                ),
            ],
            options={
                "verbose_name": "Role: Student",
                "verbose_name_plural": "Role: Student",
            },
        ),
    ]
