# Generated by Django 4.2.16 on 2024-11-13 17:52

from django.db import migrations, models
import osis_document.contrib.fields


class Migration(migrations.Migration):

    dependencies = [
        ("parcours_doctoral", "0004_alter_parcoursdoctoral_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="parcoursdoctoral",
            name="dedicated_time",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="Dedicated time (in EFT)"
            ),
        ),
        migrations.AddField(
            model_name="parcoursdoctoral",
            name="financing_comment",
            field=models.TextField(
                blank=True, default="", verbose_name="Financing comment"
            ),
        ),
        migrations.AddField(
            model_name="parcoursdoctoral",
            name="financing_eft",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="EFT"
            ),
        ),
        migrations.AddField(
            model_name="parcoursdoctoral",
            name="financing_work_contract",
            field=models.CharField(
                blank=True,
                default="",
                max_length=255,
                verbose_name="Working contract type",
            ),
        ),
        migrations.AddField(
            model_name="parcoursdoctoral",
            name="is_fnrs_fria_fresh_csc_linked",
            field=models.BooleanField(
                blank=True,
                null=True,
                verbose_name="Is your admission request linked with a FNRS, FRIA, FRESH or CSC application?",
            ),
        ),
        migrations.AddField(
            model_name="parcoursdoctoral",
            name="planned_duration",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="Planned duration"
            ),
        ),
        migrations.AddField(
            model_name="parcoursdoctoral",
            name="scholarship_end_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Scholarship end date"
            ),
        ),
        migrations.AddField(
            model_name="parcoursdoctoral",
            name="scholarship_proof",
            field=osis_document.contrib.fields.FileField(
                base_field=models.UUIDField(),
                default=list,
                size=None,
                verbose_name="Proof of scholarship",
            ),
        ),
        migrations.AddField(
            model_name="parcoursdoctoral",
            name="scholarship_start_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Scholarship start date"
            ),
        ),
    ]
