# Generated by Django 4.2.16 on 2024-12-12 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0707_django_4_migration"),
        ("parcours_doctoral", "0005_promoter_unique_constraint_data_structure"),
    ]

    operations = [
        migrations.CreateModel(
            name="EntityProxy",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("base.entity",),
        ),
        migrations.AddField(
            model_name="confirmationpaper",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Is active"),
        ),
        migrations.AddConstraint(
            model_name="confirmationpaper",
            constraint=models.UniqueConstraint(
                models.F("parcours_doctoral"),
                condition=models.Q(("is_active", True)),
                name="unique_active_confirmation_by_doctorate",
            ),
        ),
    ]
