# Generated by Django 4.2.16 on 2024-11-18 15:10

from django.db import migrations, models
import django.db.models.deletion
import osis_mail_template.models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0707_django_4_migration"),
        ("parcours_doctoral", "0006_parcoursdoctoral_dedicated_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="parcoursdoctoral",
            name="reference",
            field=models.BigIntegerField(
                editable=False, null=True, unique=True, verbose_name="Reference"
            ),
        ),
        migrations.AlterField(
            model_name="cddmailtemplate",
            name="identifier",
            field=models.CharField(
                choices=[
                    (
                        "osis-admission-generic-admitted",
                        "osis-admission-generic-admitted",
                    ),
                    (
                        "osis-parcours-doctoral-confirmation-info-student",
                        "osis-parcours-doctoral-confirmation-info-student",
                    ),
                    (
                        "osis-parcours-doctoral-confirmation-on-failure-student",
                        "osis-parcours-doctoral-confirmation-on-failure-student",
                    ),
                    (
                        "osis-parcours-doctoral-confirmation-on-retaking-student",
                        "osis-parcours-doctoral-confirmation-on-retaking-student",
                    ),
                ],
                max_length=255,
                validators=[osis_mail_template.models.check_mail_template_identifier],
                verbose_name="Identifier",
            ),
        ),
        migrations.AlterField(
            model_name="parcoursdoctoral",
            name="status",
            field=models.CharField(
                choices=[
                    ("ADMITTED", "ADMITTED"),
                    ("EN_ATTENTE_DE_SIGNATURE", "Waiting for signature"),
                    ("SUBMITTED_CONFIRMATION", "SUBMITTED_CONFIRMATION"),
                    ("PASSED_CONFIRMATION", "PASSED_CONFIRMATION"),
                    ("NOT_ALLOWED_TO_CONTINUE", "NOT_ALLOWED_TO_CONTINUE"),
                    ("CONFIRMATION_TO_BE_REPEATED", "CONFIRMATION_TO_BE_REPEATED"),
                    ("JURY_SOUMIS", "JURY_SOUMIS"),
                    ("JURY_APPROUVE_CA", "JURY_APPROUVE_CA"),
                    ("JURY_APPROUVE_CDD", "JURY_APPROUVE_CDD"),
                    ("JURY_REFUSE_CDD", "JURY_REFUSE_CDD"),
                    ("JURY_APPROUVE_ADRE", "JURY_APPROUVE_ADRE"),
                    ("JURY_REFUSE_ADRE", "JURY_REFUSE_ADRE"),
                ],
                default="ADMITTED",
                max_length=30,
                verbose_name="Status",
            ),
        ),
        migrations.CreateModel(
            name="AdreSecretary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("visible", models.BooleanField(default=True)),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="base.person",
                    ),
                ),
            ],
            options={
                "verbose_name": "Role: ADRE secretary",
                "verbose_name_plural": "Role: ADRE Secretaries",
            },
        ),
    ]
