# Generated by Django 4.2.16 on 2025-01-10 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parcours_doctoral", "0006_entityproxy_confirmationpaper_is_active_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="parcoursdoctoral",
            name="justification",
            field=models.TextField(blank=True, default="", verbose_name="Justification"),
        ),
    ]
