# Generated by Django 4.2.16 on 2025-01-27 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("parcours_doctoral", "0003_alter_parcoursdoctoral_international_scholarship"),
        ("parcours_doctoral", "0007_parcoursdoctoral_justification"),
    ]

    operations = []
