# Generated by Django 4.2.16 on 2024-11-19 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parcours_doctoral", "0007_parcoursdoctoral_reference_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="parcoursdoctoral",
            options={
                "ordering": ("-created_at",),
                "permissions": [
                    ("download_jury_approved_pdf", "Can download jury-approved PDF"),
                    ("upload_jury_approved_pdf", "Can upload jury-approved PDF"),
                    ("validate_registration", "Can validate registration"),
                    ("approve_jury", "Can approve jury"),
                    ("approve_confirmation_paper", "Can approve confirmation paper"),
                    ("validate_doctoral_training", "Can validate doctoral training"),
                    (
                        "view_admission_jury",
                        "Can view the information related to the admission jury",
                    ),
                    (
                        "change_admission_jury",
                        "Can update the information related to the admission jury",
                    ),
                    (
                        "view_confirmation",
                        "Can view the information related to the confirmation paper",
                    ),
                    (
                        "change_admission_confirmation",
                        "Can update the information related to the confirmation paper",
                    ),
                ],
                "verbose_name": "Doctorate admission",
            },
        ),
        migrations.AddField(
            model_name="parcoursdoctoral",
            name="proximity_commission",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ECONOMY", "ECONOMY"),
                    ("MANAGEMENT", "MANAGEMENT"),
                    (
                        "ECLI",
                        "Proximity commission for experimental and clinical research (ECLI)",
                    ),
                    ("GIM", "Proximity Commission for Genetics and Immunology (GIM)"),
                    ("NRSC", "Proximity Commission for Neuroscience (NRSC)"),
                    (
                        "BCM",
                        "Proximity commission for cellular and molecular biology, biochemistry (BCM)",
                    ),
                    (
                        "SPSS",
                        "Proximity commission for public health, health and society (SPSS)",
                    ),
                    ("DENT", "Proximity Commission for Dental Sciences (DENT)"),
                    ("DFAR", "Proximity Commission for Pharmaceutical Sciences (DFAR)"),
                    ("MOTR", "Proximity Commission for Motricity Sciences (MOTR)"),
                    ("PHYSICS", "PHYSICS"),
                    ("CHEMISTRY", "CHEMISTRY"),
                    ("MATHEMATICS", "MATHEMATICS"),
                    ("STATISTICS", "STATISTICS"),
                    ("BIOLOGY", "BIOLOGY"),
                    ("GEOGRAPHY", "GEOGRAPHY"),
                ],
                default="",
                max_length=255,
                verbose_name="Proximity commission",
            ),
        ),
    ]
