# Generated by Django 4.2.16 on 2025-02-04 10:41

import osis_document.contrib.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parcours_doctoral", "0008_merge_20250127_1311"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="hour_volume_type",
            field=models.CharField(
                blank=True,
                choices=[("HEURES", "hours"), ("JOURS", "days")],
                default="",
                max_length=100,
                verbose_name="Hourly volume type",
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="is_publication_national",
            field=models.BooleanField(
                blank=True,
                choices=[
                    (False, "International publication"),
                    (True, "National publication"),
                ],
                default=None,
                null=True,
                verbose_name="Is publication national",
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="mark",
            field=models.CharField(
                blank=True,
                default="",
                max_length=100,
                verbose_name="Mark or honours obtained",
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="with_reading_committee",
            field=models.BooleanField(
                blank=True,
                choices=[
                    (False, "Without reading committee"),
                    (True, "With reading committee"),
                ],
                default=None,
                null=True,
                verbose_name="With reading committee",
            ),
        ),
        migrations.AlterField(
            model_name="activity",
            name="journal",
            field=models.CharField(
                blank=True,
                default="",
                max_length=100,
                verbose_name="Journal, publishing house or depository institution",
            ),
        ),
        migrations.AlterField(
            model_name="activity",
            name="participating_proof",
            field=osis_document.contrib.fields.FileField(
                base_field=models.UUIDField(),
                blank=True,
                default=list,
                size=2,
                verbose_name="Participation certification",
            ),
        ),
        migrations.AlterField(
            model_name="activity",
            name="publication_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("UNSUBMITTED", "Unsubmitted"),
                    ("SUBMITTED", "Submitted"),
                    ("IN_REVIEW", "Awaiting approval"),
                    ("DEPOSITED", "Deposited"),
                    ("ACCEPTED", "Accepted"),
                    ("PUBLISHED", "Published"),
                ],
                default="",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="activity",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("AUTERTRICE_UNIQUE", "Only author"),
                    ("COAUTEURTRICE", "Co-author"),
                    ("PREMIER_AUTEURTRICE", "First author"),
                    ("DEUXIEME_AUTEURTRICE", "Second author"),
                    ("EDITEURTRICE", "Editor"),
                    ("COEDITEURTRICE", "Co-editor"),
                ],
                default="",
                max_length=100,
                verbose_name="Role",
            ),
        ),
    ]
