# Generated by Django 4.2.16 on 2025-02-10 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("parcours_doctoral", "0008_merge_20250127_1311"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="parcoursdoctoral",
            options={
                "ordering": ("-created_at",),
                "permissions": [
                    ("validate_registration", "Can validate registration"),
                    ("approve_jury", "Can approve jury"),
                    ("approve_confirmation_paper", "Can approve confirmation paper"),
                    ("validate_doctoral_training", "Can validate doctoral training"),
                    (
                        "view_admission_jury",
                        "Can view the information related to the admission jury",
                    ),
                    (
                        "change_admission_jury",
                        "Can update the information related to the admission jury",
                    ),
                    (
                        "view_confirmation",
                        "Can view the information related to the confirmation paper",
                    ),
                    (
                        "change_admission_confirmation",
                        "Can update the information related to the confirmation paper",
                    ),
                ],
                "verbose_name": "Doctoral training",
            },
        ),
    ]
