# Generated by Django 4.2.16 on 2025-02-19 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parcours_doctoral", "0009_alter_parcoursdoctoral_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="context",
            field=models.CharField(
                choices=[
                    ("DOCTORAL_TRAINING", "DOCTORAL_TRAINING"),
                    ("COMPLEMENTARY_TRAINING", "COMPLEMENTARY_TRAINING"),
                ],
                default="DOCTORAL_TRAINING",
                max_length=30,
                verbose_name="Context",
            ),
        ),
    ]
