# Generated by Django 4.2.16 on 2025-01-30 18:06

import uuid

import django.db.models.deletion
import osis_document.contrib.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0708_educationgroupyear_type_de_ponderation"),
        ("parcours_doctoral", "0009_alter_parcoursdoctoral_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255,
                        verbose_name="Name",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        verbose_name="Updated at",
                    ),
                ),
                (
                    "file",
                    osis_document.contrib.fields.FileField(
                        base_field=models.UUIDField(),
                        default=list,
                        size=1,
                        verbose_name="File",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("LIBRE", "Free"),
                            ("NON_LIBRE", "Not free"),
                            ("SYSTEME", "Generated by the system"),
                        ],
                        max_length=255,
                        verbose_name="Document type",
                    ),
                ),
                (
                    "related_doctorate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="parcours_doctoral.parcoursdoctoral",
                        verbose_name="Related doctorate",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="base.person",
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Document",
                "verbose_name_plural": "Documents",
            },
        ),
    ]
