# Generated by Django 4.2.16 on 2025-02-19 14:26

import uuid

import django.db.models.deletion
from django.db import migrations, models

import parcours_doctoral.ddd.formation.domain.model.enums


class Migration(migrations.Migration):

    dependencies = [
        ("parcours_doctoral", "0009_alter_parcoursdoctoral_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssessmentEnrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                    ),
                ),
                (
                    "session",
                    models.CharField(
                        choices=[
                            ("JANUARY", "January"),
                            ("JUNE", "June"),
                            ("SEPTEMBER", "September"),
                        ],
                        max_length=255,
                        verbose_name="Session",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACCEPTEE", "ACCEPTEE"),
                            ("DESINSCRITE", "DESINSCRITE"),
                        ],
                        max_length=255,
                        verbose_name="Status",
                    ),
                ),
                (
                    "late_enrollment",
                    models.BooleanField(verbose_name="Late enrollment"),
                ),
                (
                    "course",
                    models.ForeignKey(
                        limit_choices_to=models.Q(
                            (
                                "category",
                                parcours_doctoral.ddd.formation.domain.model.enums.CategorieActivite["UCL_COURSE"].name,
                            )
                        ),
                        on_delete=django.db.models.deletion.CASCADE,
                        to="parcours_doctoral.activity",
                        verbose_name="Course",
                    ),
                ),
            ],
        ),
    ]
