# Generated by Django 4.2.16 on 2025-02-06 16:40

from django.db import migrations, models
from django.db.models import Q


def update_doctorate_enums_values(apps, schema_editor):
    ParcoursDoctoral = apps.get_model('parcours_doctoral', 'ParcoursDoctoral')

    ParcoursDoctoral.objects.filter(phd_already_done='PARTIAL').update(phd_already_done='YES')

    ParcoursDoctoral.objects.filter(Q(proximity_commission='BCM') | Q(proximity_commission='GIM')).update(
        proximity_commission='BCGIM'
    )


class Migration(migrations.Migration):

    dependencies = [
        ('parcours_doctoral', '0011_activity_hour_volume_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parcoursdoctoral',
            options={
                'ordering': ('-created_at',),
                'permissions': [
                    ('validate_registration', 'Can validate registration'),
                    ('approve_jury', 'Can approve jury'),
                    ('approve_confirmation_paper', 'Can approve confirmation paper'),
                    ('validate_doctoral_training', 'Can validate doctoral training'),
                    (
                        'view_admission_jury',
                        'Can view the information related to the admission jury',
                    ),
                    (
                        'change_admission_jury',
                        'Can update the information related to the admission jury',
                    ),
                    (
                        'view_confirmation',
                        'Can view the information related to the confirmation paper',
                    ),
                    (
                        'change_admission_confirmation',
                        'Can update the information related to the confirmation paper',
                    ),
                ],
                'verbose_name': 'Doctoral training',
            },
        ),
        migrations.AlterField(
            model_name='parcoursdoctoral',
            name='phd_already_done',
            field=models.CharField(
                blank=True,
                choices=[('YES', 'YES'), ('NO', 'NO')],
                default='NO',
                max_length=255,
                verbose_name='PhD already done',
            ),
        ),
        migrations.AlterField(
            model_name='parcoursdoctoral',
            name='proximity_commission',
            field=models.CharField(
                blank=True,
                choices=[
                    ('ECONOMY', 'ECONOMY'),
                    ('MANAGEMENT', 'MANAGEMENT'),
                    (
                        'ECLI',
                        'Proximity commission for experimental and clinical research (ECLI)',
                    ),
                    (
                        'BCGIM',
                        'Proximity commission for biochemistry, cellular and molecular biology, '
                        'genetics, immunology (BCGIM)',
                    ),
                    ('NRSC', 'Proximity Commission for Neuroscience (NRSC)'),
                    (
                        'SPSS',
                        'Proximity commission for public health, health and society (SPSS)',
                    ),
                    ('DENT', 'Proximity Commission for Dental Sciences (DENT)'),
                    ('DFAR', 'Proximity Commission for Pharmaceutical Sciences (DFAR)'),
                    ('MOTR', 'Proximity Commission for Motricity Sciences (MOTR)'),
                    ('PHYSICS', 'PHYSICS'),
                    ('CHEMISTRY', 'CHEMISTRY'),
                    ('MATHEMATICS', 'MATHEMATICS'),
                    ('STATISTICS', 'STATISTICS'),
                    ('BIOLOGY', 'BIOLOGY'),
                    ('GEOGRAPHY', 'GEOGRAPHY'),
                ],
                default="",
                max_length=255,
                verbose_name='Proximity commission',
            ),
        ),
        migrations.RunPython(code=update_doctorate_enums_values, reverse_code=migrations.RunPython.noop),
    ]
