# Generated by Django 4.2.20 on 2025-04-02 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("admission", "0253_promoter_unique_constraint_data_structure"),
        ("parcours_doctoral", "0015_alter_parcoursdoctoral_status"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CommitteeMember",
        ),
        migrations.DeleteModel(
            name="Promoter",
        ),
        migrations.CreateModel(
            name="CommitteeMember",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("admission.committeemember",),
        ),
        migrations.CreateModel(
            name="Promoter",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("admission.promoter",),
        ),
    ]
