# Generated by Django 4.2.20 on 2025-05-13 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parcours_doctoral", "0016_proxy_promoter_committeemember_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="assessmentenrollment",
            name="late_unenrollment",
            field=models.BooleanField(default=False, verbose_name="Late unenrollment"),
        ),
        migrations.AddField(
            model_name="assessmentenrollment",
            name="mark",
            field=models.CharField(default="", verbose_name="Mark", blank=True),
        ),
    ]
