# Generated by Django 4.2.20 on 2025-06-11 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reference", "0019_scholarship"),
        ("parcours_doctoral", "0018_activity_learning_class_year"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="parcoursdoctoral",
            name="defense_language",
        ),
        migrations.AddField(
            model_name="parcoursdoctoral",
            name="defense_language",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="reference.language",
                verbose_name="Defence language",
            ),
        ),
        migrations.AlterField(
            model_name="parcoursdoctoral",
            name="thesis_language",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="reference.language",
                verbose_name="Thesis language",
            ),
        ),
        migrations.AlterField(
            model_name="jurymember",
            name="title",
            field=models.CharField(
                blank=True,
                choices=[
                    ("DOCTEUR", "Doctor"),
                    ("PROFESSEUR", "Professor"),
                    ("NON_DOCTEUR", "Without PhD degree"),
                ],
                default="",
                max_length=50,
                verbose_name="Title",
            ),
        ),
        migrations.RemoveField(
            model_name="parcoursdoctoral",
            name="defense_indicative_date",
        ),
        migrations.AddField(
            model_name="parcoursdoctoral",
            name="defense_indicative_date",
            field=models.CharField(
                blank=True,
                default="",
                max_length=255,
                verbose_name="Defence indicative date",
            ),
        ),
    ]
