# Generated by Django 4.2.20 on 2025-08-22 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning_unit", "0018_mail_echeance_modification_description_fiches"),
        ("parcours_doctoral", "0017_assessmentenrollment_late_unenrollment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="learning_class_year",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="learning_unit.learningclassyear",
            ),
        ),
    ]
