# Generated by Django 4.2.20 on 2025-07-04 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parcours_doctoral", "0017_assessmentenrollment_late_unenrollment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assessmentenrollment",
            name="submitted_mark",
            field=models.CharField(blank=True, default="", max_length=20, verbose_name="Submitted mark"),
        ),
    ]
