# Generated by Django 4.2.20 on 2025-06-11 15:37

import uuid

import django.db.models.deletion
import osis_document.contrib.fields
from django.db import migrations, models


def initialise_private_defenses(apps, _):
    PrivateDefense = apps.get_model('parcours_doctoral', 'PrivateDefense')
    ParcoursDoctoral = apps.get_model('parcours_doctoral', 'ParcoursDoctoral')

    private_defenses = [
        PrivateDefense(
            parcours_doctoral=doctorate,
            current_parcours_doctoral=doctorate,
        )
        for doctorate in ParcoursDoctoral.objects.all()
    ]

    PrivateDefense.objects.bulk_create(private_defenses)


class Migration(migrations.Migration):

    dependencies = [
        ("parcours_doctoral", "0017_assessmentenrollment_late_unenrollment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parcoursdoctoral",
            name="status",
            field=models.CharField(
                choices=[
                    ("ADMIS", "ADMIS"),
                    ("EN_ATTENTE_DE_SIGNATURE", "EN_ATTENTE_DE_SIGNATURE"),
                    ("CONFIRMATION_SOUMISE", "CONFIRMATION_SOUMISE"),
                    ("CONFIRMATION_REUSSIE", "CONFIRMATION_REUSSIE"),
                    ("NON_AUTORISE_A_POURSUIVRE", "NON_AUTORISE_A_POURSUIVRE"),
                    ("CONFIRMATION_A_REPRESENTER", "CONFIRMATION_A_REPRESENTER"),
                    ("JURY_SOUMIS", "JURY_SOUMIS"),
                    ("JURY_APPROUVE_CA", "JURY_APPROUVE_CA"),
                    ("JURY_APPROUVE_CDD", "JURY_APPROUVE_CDD"),
                    ("JURY_REFUSE_CDD", "JURY_REFUSE_CDD"),
                    ("JURY_APPROUVE_ADRE", "JURY_APPROUVE_ADRE"),
                    ("JURY_REFUSE_ADRE", "JURY_REFUSE_ADRE"),
                    ("DEFENSE_PRIVEE_SOUMISE", "DEFENSE_PRIVEE_SOUMISE"),
                    ("DEFENSE_PRIVEE_AUTORISEE", "DEFENSE_PRIVEE_AUTORISEE"),
                    ("DEFENSE_PRIVEE_A_RECOMMENCER", "DEFENSE_PRIVEE_A_RECOMMENCER"),
                    ("DEFENSE_PRIVEE_REUSSIE", "DEFENSE_PRIVEE_REUSSIE"),
                    ("ABANDON", "ABANDON"),
                ],
                default="ADMIS",
                max_length=64,
                verbose_name="Status",
            ),
        ),
        migrations.CreateModel(
            name="PrivateDefense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "datetime",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Private defence date and time",
                    ),
                ),
                (
                    "place",
                    models.TextField(blank=True, default="", verbose_name="Private defence location"),
                ),
                (
                    "manuscript_submission_date",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Date of manuscript submission to the thesis exam board",
                    ),
                ),
                (
                    "minutes",
                    osis_document.contrib.fields.FileField(
                        base_field=models.UUIDField(),
                        default=list,
                        size=None,
                        verbose_name="Private defence minutes",
                    ),
                ),
                (
                    "minutes_canvas",
                    osis_document.contrib.fields.FileField(
                        base_field=models.UUIDField(),
                        default=list,
                        size=None,
                        verbose_name="Private defence minutes canvas",
                    ),
                ),
                (
                    "current_parcours_doctoral",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="current_private_defense",
                        to="parcours_doctoral.parcoursdoctoral",
                        verbose_name="Doctorate whose this private defense is the active one",
                    ),
                ),
                (
                    "parcours_doctoral",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="parcours_doctoral.parcoursdoctoral",
                        verbose_name="Doctorate",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.RunPython(
            code=initialise_private_defenses,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
