# Generated by Django 4.2.20 on 2025-06-20 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0711_delete_etatfinancabilite2023"),
        ("parcours_doctoral", "0018_alter_parcoursdoctoral_defense_language_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Auditor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("visible", models.BooleanField(default=True)),
                (
                    "entity",
                    models.OneToOneField(
                        limit_choices_to={"organization__type": "MAIN"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="base.entity",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="base.person",
                    ),
                ),
            ],
            options={
                "verbose_name": "Role: Auditor",
            },
        ),
        migrations.CreateModel(
            name="SectorAdministrativeDirector",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("visible", models.BooleanField(default=True)),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="base.person",
                    ),
                ),
            ],
            options={
                "verbose_name": "Role: Sector administrative director",
                "verbose_name_plural": "Role: Sector administrative directors",
            },
        ),
    ]
