# Generated by Django 4.2.24 on 2025-10-23 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("admission", "0271_doctorate_manager_submission_mail_template"),
        ("parcours_doctoral", "0018_activity_learning_class_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parcoursdoctoral",
            name="admission",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="admission.doctorateadmission",
                verbose_name="Admission",
            ),
        ),
    ]
