# Generated by Django 4.2.16 on 2025-03-19 16:15
from django.db import migrations

from parcours_doctoral.utils.doctorates_initialization_from_authorized_admissions import (
    initialize_the_doctorates_from_authorized_admissions,
)


def initialize_the_doctorates_from_authorized_admissions_migration(apps, schema_editor):
    DoctorateAdmission = apps.get_model("admission", "DoctorateAdmission")
    initialize_the_doctorates_from_authorized_admissions(
        doctorate_admission_model=DoctorateAdmission,
        on_migration=True,
    )


class Migration(migrations.Migration):

    dependencies = [
        ("parcours_doctoral", "0019_alter_parcoursdoctoral_admission"),
    ]

    operations = [
        migrations.RunPython(
            code=initialize_the_doctorates_from_authorized_admissions_migration,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
