# Generated by Django 4.2.20 on 2025-07-03 15:38

from django.db import migrations
from osis_mail_template import MailTemplateMigration

from parcours_doctoral.mail_templates import (
    PARCOURS_DOCTORAL_JURY_EMAIL_SIGNATURE_REQUESTS_MEMBER,
    PARCOURS_DOCTORAL_JURY_EMAIL_SIGNATURE_REQUESTS_PROMOTER,
)
from parcours_doctoral.mail_templates.jury import (
    PARCOURS_DOCTORAL_JURY_EMAIL_MEMBER_REFUSAL,
)


class Migration(migrations.Migration):

    dependencies = [
        ("parcours_doctoral", "0020_juryactor_parcoursdoctoral_jury_group_and_more"),
    ]

    operations = [
        MailTemplateMigration(
            PARCOURS_DOCTORAL_JURY_EMAIL_SIGNATURE_REQUESTS_PROMOTER,
            {
                'en': '[OSIS] Invitation to approve {student_first_name} {student_last_name}’s thesis board for {training_title}',
                'fr-be': '[OSIS] Invitation à approuver le jury de thèse {student_first_name} {student_last_name}  pour un {training_title}',
            },
            {
                'en': '''<p>Professor {signataire_first_name} {signataire_last_name},</p>

<p>{student_first_name} {student_last_name} completed a thesis board membership application for {training_title}.</p>

<p>To view the proposed board membership and indicate your approval or refusal, please click on this link: <a href="{parcours_doctoral_link_front}">{parcours_doctoral_link_front}</a></p>

<p>By validating the board membership, you confirm that you have sufficient means to cover the costs associated with organising the thesis defence.</p>

<p>Please contact us should you require further information.</p>

<p>Sincerely,</p>

<p>{cdd_manager_names} - {doctoral_commission}</p>
                ''',
                'fr-be': '''<p>Professeur.e {signataire_first_name} {signataire_last_name},</p>

<p>{student_first_name} {student_last_name} a complété sa demande de jury pour son {training_title}.</p>

<p>Pour visualiser la composition proposée et indiquer votre approbation ou refus, merci de cliquer sur ce lien: <a href="{parcours_doctoral_link_front}">{parcours_doctoral_link_front}</a></p>

<p>En validant cette composition de jury, vous confirmez que vous disposez des moyens suffisants pour couvrir les frais liés à l’organisation de la fin de thèse.</p>

<p>Nous restons à votre disposition pour tout autre renseignement complémentaire.</p>

<p>Bien cordialement.</p>

<p>{cdd_manager_names} - {doctoral_commission}</p>
                ''',
            },
        ),
        MailTemplateMigration(
            PARCOURS_DOCTORAL_JURY_EMAIL_SIGNATURE_REQUESTS_MEMBER,
            {
                'en': '[OSIS] Invitation to approve {student_first_name} {student_last_name}’s thesis board for {training_title}',
                'fr-be': '[OSIS] Invitation à approuver le jury de thèse {student_first_name} {student_last_name} pour un {training_title}',
            },
            {
                'en': '''<p>Dear {signataire_first_name} {signataire_last_name}, {student_first_name} {student_last_name} has completed a thesis board membership application for {training_title}.</p>

<p>To view the proposed membership and indicate your approval or refusal, please click on this link: <a href="{parcours_doctoral_link_front}">{parcours_doctoral_link_front}</a></p>

<p>Please contact us should you require further information. Sincerely,</p>

<p>{cdd_manager_names} - {doctoral_commission}</p>
                ''',
                'fr-be': '''<p>Cher, Chère, Cher.ère {signataire_first_name} {signataire_last_name}, {student_first_name} {student_last_name} a complété sa demande de jury pour son {training_title}.</p>

<p>Pour visualiser la composition proposée et indiquer votre approbation ou refus, merci de cliquer sur ce lien : <a href="{parcours_doctoral_link_front}">{parcours_doctoral_link_front}</a></p>

<p>Nous restons à votre disposition pour tout autre renseignement complémentaire. Bien cordialement.</p>

<p>---</p>

<p>{cdd_manager_names} - {doctoral_commission}</p>
                ''',
            },
        ),
        MailTemplateMigration(
            PARCOURS_DOCTORAL_JURY_EMAIL_MEMBER_REFUSAL,
            {
                'en': '[OSIS] Refusal of {student_first_name} {student_last_name}’s thesis board proposal for {training_title}',
                'fr-be': '[OSIS] Refus de proposition de jury {student_first_name} {student_last_name}  pour un {training_title}',
            },
            {
                'en': '''<p>Dear {student_first_name} {student_last_name},</p>

<p>{signataire_first_name} {signataire_last_name} has refused the thesis board membership proposal for your {training_title} for the following reason: {refusal_reason}</p>

<p>Please submit a new proposal via your virtual office.</p>

<p>Please contact us should you require further information.</p>

<p>Sincerely,</p>

<p>{cdd_manager_names} - {doctoral_commission}</p>
                ''',
                'fr-be': '''Cher, Chère, Cher.ère, {student_first_name} {student_last_name},</p>

{signataire_first_name} {signataire_last_name} a refusé la proposition de composition de jury de thèse pour votre {training_title}, pour le motif suivant : {refusal_reason}</p>

Nous vous invitons à soumettre une nouvelle proposition via votre bureau virtuel.</p>

Nous restons à votre disposition pour tout autre renseignement complémentaire.</p>

Bien cordialement,</p>

{cdd_manager_names} - {doctoral_commission}</p>
                ''',
            },
        ),
    ]
