# Generated by Django 4.2.20 on 2025-08-28 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parcours_doctoral", "0020_auto_20250703_1538"),
    ]

    operations = [
        migrations.AddField(
            model_name="juryactor",
            name="is_lead_promoter",
            field=models.BooleanField(blank=True, default=False, verbose_name="Is the lead promoter"),
        ),
    ]
