# Generated by Django 4.2.20 on 2025-09-03 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0714_sicmanagement"),
        ("parcours_doctoral", "0021_juryactor_is_lead_promoter"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditor",
            name="with_child",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="auditor",
            name="entity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="base.entity",
            ),
        ),
    ]
