# Generated by Django 4.2.20 on 2025-07-02 12:18

import django.db.models.deletion
import osis_document_components.fields
import osis_signature.contrib.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("osis_signature", "0003_external_actor"),
        ("parcours_doctoral", "0022_auditor"),
    ]

    operations = [
        migrations.CreateModel(
            name="JuryActor",
            fields=[
                (
                    "actor_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="osis_signature.actor",
                    ),
                ),
                (
                    "is_promoter",
                    models.BooleanField(blank=True, default=False, verbose_name="Is a promoter"),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("PRESIDENT", "PRESIDENT"),
                            ("SECRETAIRE", "SECRETAIRE"),
                            ("MEMBRE", "MEMBRE"),
                            ("VERIFICATEUR", "VERIFICATEUR"),
                        ],
                        max_length=50,
                        verbose_name="Role",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("DOCTEUR", "Doctor"),
                            ("PROFESSEUR", "Professor"),
                            ("NON_DOCTEUR", "Without PhD degree"),
                        ],
                        default="",
                        max_length=50,
                        verbose_name="Title",
                    ),
                ),
                (
                    "non_doctor_reason",
                    models.TextField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Non doctor reason",
                    ),
                ),
                (
                    "other_institute",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Other institute",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("FEMININ", "Female"),
                            ("MASCULIN", "Male"),
                            ("AUTRE", "Other"),
                        ],
                        max_length=50,
                        verbose_name="Gender",
                    ),
                ),
                (
                    "internal_comment",
                    models.TextField(blank=True, default="", verbose_name="Internal comment"),
                ),
                (
                    "rejection_reason",
                    models.CharField(blank=True, default="", max_length=50, verbose_name="Grounds for denied"),
                ),
                (
                    "pdf_from_candidate",
                    osis_document_components.fields.FileField(
                        base_field=models.UUIDField(),
                        default=list,
                        size=1,
                        verbose_name="PDF file",
                    ),
                ),
            ],
            bases=("osis_signature.actor",),
        ),
        migrations.AddField(
            model_name="parcoursdoctoral",
            name="jury_group",
            field=osis_signature.contrib.fields.SignatureProcessField(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="osis_signature.process",
            ),
        ),
        migrations.AlterField(
            model_name="parcoursdoctoral",
            name="supervision_group",
            field=osis_signature.contrib.fields.SignatureProcessField(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="osis_signature.process",
            ),
        ),
        migrations.DeleteModel(
            name="JuryMember",
        ),
        migrations.CreateModel(
            name="JuryMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("visible", models.BooleanField(default=True)),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="base.person",
                    ),
                ),
            ],
            options={
                "verbose_name": "Role: Jury member",
                "verbose_name_plural": "Role: Jury members",
            },
        ),
        migrations.AddConstraint(
            model_name="jurymember",
            constraint=models.UniqueConstraint(
                fields=("person",),
                name="parcours_doctoral_unique_jury_member_by_person",
            ),
        ),
    ]
