# Generated by Django 4.2.20 on 2025-09-12 10:30

from django.db import migrations
from osis_mail_template import MailTemplateMigration

from parcours_doctoral.mail_templates.jury import (
    PARCOURS_DOCTORAL_JURY_EMAIL_ADRE_APPROVAL,
    PARCOURS_DOCTORAL_JURY_EMAIL_ADRE_REFUSAL,
    PARCOURS_DOCTORAL_JURY_EMAIL_CDD_APPROVAL,
    PARCOURS_DOCTORAL_JURY_EMAIL_CDD_REFUSAL,
)


class Migration(migrations.Migration):

    dependencies = [
        ("parcours_doctoral", "0023_auditor_with_child_alter_auditor_entity"),
    ]

    operations = [
        MailTemplateMigration(
            PARCOURS_DOCTORAL_JURY_EMAIL_CDD_REFUSAL,
            {
                'en': '[OSIS] Refusal of {student_first_name} {student_last_name}’s thesis board proposal for {training_title}',
                'fr-be': "[OSIS] Refus de proposition de jury {student_first_name} {student_last_name} pour un {training_title}",
            },
            {
                'en': '''<p>Dear {student_first_name} {student_last_name},</p>

<p>After examination by the PhD Field Committee {signataire_first_name} {signataire_last_name} your thesis board membership proposal for your {training_title} has been refused for the following reason: {refusal_reason}.</p>

<p>Please submit a new proposal via your virtual office.</p>

<p>Please contact us should you require further information.</p>

<p>Sincerely,</p>

<p>{cdd_manager_names} - {doctoral_commission}</p>
            ''',
                'fr-be': '''<p>Cher, Chère, Cher.ère, {student_first_name} {student_last_name},</p>

<p>Après examen par la Commission doctorale de votre domaine, votre proposition de composition de jury de thèse pour votre {training_title} a été refusée pour le motif suivant : {refusal_reason}.</p>

<p>Nous vous invitons à soumettre une nouvelle proposition via votre bureau virtuel.</p>

<p>Nous restons à votre disposition pour tout autre renseignement complémentaire.</p>

<p>Bien cordialement,</p>

<p>{cdd_manager_names} - {doctoral_commission}</p>
            ''',
            },
        ),
        MailTemplateMigration(
            PARCOURS_DOCTORAL_JURY_EMAIL_CDD_APPROVAL,
            {
                'en': '[OSIS] Approval of {student_first_name} {student_last_name}’s thesis board proposal for {training_title}',
                'fr-be': "[OSIS] Approbation de proposition de jury {student_first_name} {student_last_name}  pour un {training_title}",
            },
            {
                'en': '''<p>Dear colleagues,</p>

<p>The proposed thesis board membership for {student_first_name} {student_last_name} has been approved by the PhD Field Committee (CDD).</p>

<p>Please have this proposal validated by the academic authorities.

<p>Here is the link to the dossier {parcours_doctoral_link_front_jury}.</p>

<p>Please contact us should you require further information.

<p>Sincerely,</p>

<p>{cdd_manager_names} - {doctoral_commission}</p>
            ''',
                'fr-be': '''<p>Cher, Chère, Cher.ère collègues,</p>

<p>La proposition de composition de jury de thèse de {student_first_name} {student_last_name} a été approuvée par la CDD.
Nous vous remercions de faire valider cette proposition par les autorités académiques.</p>

<p>Voici le lien vers le dossier {parcours_doctoral_link_front_jury}.</p>

<p>Nous restons à votre disposition pour tout autre renseignement complémentaire.</p>

<p>Bien cordialement,</p>

<p>{cdd_manager_names} - {doctoral_commission}</p>
            ''',
            },
        ),
        MailTemplateMigration(
            PARCOURS_DOCTORAL_JURY_EMAIL_ADRE_REFUSAL,
            {
                'en': '[OSIS] Refusal of {student_first_name} {student_last_name}’s thesis board proposal for {training_title}',
                'fr-be': "[OSIS] Refus de proposition de jury {student_first_name} {student_last_name}  pour un {training_title}",
            },
            {
                'en': '''<p>Dear {student_first_name} {student_last_name},</p>

<p>After examination of your application, the academic authorities have refused your thesis board membership proposal for the following reason: {refusal_reason}.</p>

<p>Please submit a new proposal via your virtual office.</p>

<p>Please contact us should you require further information.</p>

<p>Sincerely,</p>

<p>{adre_manager_name}</p>
            ''',
                'fr-be': '''<p>Cher, Chère, Cher.ère, {student_first_name} {student_last_name},</p>

<p>Après examen de votre demande, les autorités académiques ont refusé votre proposition de composition de jury de thèse, pour le motif suivant : {refusal_reason}</p>

<p>Nous vous invitons à soumettre une nouvelle proposition via votre bureau virtuel.</p>

<p>Nous restons à votre disposition pour tout autre renseignement complémentaire.</p>

<p>Bien cordialement,</p>

<p>{adre_manager_name}</p>
            ''',
            },
        ),
        MailTemplateMigration(
            PARCOURS_DOCTORAL_JURY_EMAIL_ADRE_APPROVAL,
            {
                'en': '[OSIS] Approval of {student_first_name} {student_last_name}’s thesis board proposal for {training_title}',
                'fr-be': "[OSIS] Approbation de proposition de jury {student_first_name} {student_last_name} pour un {training_title}",
            },
            {
                'en': '''<p>Dear {student_first_name} {student_last_name},</p>

<p>After examination of your application, the academic authorities have approved your thesis board membership proposal.</p>

<p>To view the board membership, please click on this link {parcours_doctoral_link_front_jury}.</p>

<p>Please contact us should you require further information.</p>

<p>Sincerely,</p>

<p>{adre_manager_name}</p>
            ''',
                'fr-be': '''<p>Cher, Chère, Cher.ère, {student_first_name} {student_last_name},</p>

<p>Après examen de votre demande, les autorités académiques ont approuvé votre proposition de composition de jury de thèse.</p>

<p>Pour visualiser cette composition, merci de cliquer sur ce lien {parcours_doctoral_link_front_jury}.
Votre gestionnaire de doctorat reste à votre disposition pour tout autre renseignement complémentaire.</p>

<p>Bien cordialement,</p>

<p>{adre_manager_name}</p>
            ''',
            },
        ),
    ]
