# Generated by Django 4.2.20 on 2025-09-22 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0717_update_dates_calendrier_academique"),
        ("parcours_doctoral", "0024_mails_jury_cdd_adre"),
    ]

    operations = [
        migrations.AlterField(
            model_name="juryactor",
            name="role",
            field=models.CharField(
                choices=[
                    ("PRESIDENT", "PRESIDENT"),
                    ("SECRETAIRE", "SECRETAIRE"),
                    ("MEMBRE", "MEMBRE"),
                    ("VERIFICATEUR", "VERIFICATEUR"),
                    ("CDD", "CDD"),
                    ("ADRE", "ADRE"),
                ],
                max_length=50,
                verbose_name="Role",
            ),
        ),
        migrations.CreateModel(
            name="AdreManager",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("visible", models.BooleanField(default=True)),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="base.person",
                    ),
                ),
            ],
            options={
                "verbose_name": "Role: ADRE manager",
                "verbose_name_plural": "Role: ADRE managers",
            },
        ),
    ]
