# Generated by Django 4.2.20 on 2025-09-09 16:03

from django.db import migrations
from osis_mail_template import MailTemplateMigration

from parcours_doctoral.mail_templates.private_defense import *


class Migration(migrations.Migration):

    dependencies = [
        (
            "parcours_doctoral",
            "0026_alter_parcoursdoctoral_status_privatedefense_and_more",
        ),
    ]

    operations = [
        MailTemplateMigration(
            PARCOURS_DOCTORAL_EMAIL_PRIVATE_DEFENSE_AUTHORISATION,
            {
                'en': 'Private defence authorisation for {student_first_name} {student_last_name}',
                'fr-be': 'Défense privée autorisée {student_first_name} {student_last_name}',
            },
            {
                'en': '''\
<p>Dear {student_first_name} {student_last_name},</p>
<p>The PhD Field Committee takes note that your private defence for your {training_title} will take place on {private_defense_date}.</p>
<p>Please contact us should you require further information.</p>
<p>Sincerely,</p>
<p>{sender_name} - {management_entity_name}</p>''',
                'fr-be': '''\
<p>Cher, Chère, Cher.ère {student_first_name} {student_last_name},</p>
<p>La Commission doctorale de votre domaine prend note que votre défense privée pour votre {training_title} aura lieu le {private_defense_date}.</p>
<p>Nous restons à votre disposition pour tout autre renseignement complémentaire.</p>
<p>Bien cordialement.</p>
<p>---</p>
<p>{sender_name} - {management_entity_name}</p>''',
            },
        ),
        MailTemplateMigration(
            PARCOURS_DOCTORAL_EMAIL_PRIVATE_DEFENSE_JURY_INVITATION,
            {
                'en': 'Private defence invitation for {student_first_name} {student_last_name}',
                'fr-be': 'Convocation défense privée {student_first_name} {student_last_name}',
            },
            {
                'en': '''\
<p>Dear {jury_member_first_name} {jury_member_last_name},</p>
<p>{student_first_name} {student_last_name} will present the private thesis defence for {training_title} on {private_defense_date} in room {private_defense_place}.</p>
<p>We remind you that, as a board member, you are required to attend either in person or by videoconference.</p>
<p>Further details will be sent to you at a later date concerning your reception and the day's practical organisation.</p>
<p>Thank you in advance for your important contribution.</p>
<p>Please contact me should you require further information.</p>
<p>Sincerely,</p>
<p>{sender_name} - {management_entity_name}</p>''',
                'fr-be': '''\
<p>Cher, Chère, Cher.ère {jury_member_first_name} {jury_member_last_name},</p>
<p>{student_first_name} {student_last_name} présentera sa défense privée pour son {training_title} le {private_defense_date}, dans le local {private_defense_place}.</p>
<p>Nous vous rappelons qu'en tant que membre du jury, votre présence lors de cette épreuve est requise physiquement ou en visioconférence.</p>
<p>De plus amples détails vous parviendront ultérieurement concernant votre accueil et l'organisation pratique de cette journée.</p>
<p>En vous remerciant d'avance pour votre contribution importante, je vous adresse mes plus cordiales
salutations et reste bien entendu à votre entière disposition.</p>
<p>---</p>
<p>{sender_name} - {management_entity_name}</p>''',
            },
        ),
        MailTemplateMigration(
            PARCOURS_DOCTORAL_EMAIL_PRIVATE_DEFENSE_ON_SUCCESS,
            {
                'en': 'Successful thesis defence for {student_first_name} {student_last_name}',
                'fr-be': 'Réussite défense privée {student_first_name} {student_last_name}',
            },
            {
                'en': '''\
<p>Dear {student_first_name} {student_last_name},</p>
<p>Following your private defence, the board members have judged your thesis to be admissible, subject to the modifications to be made to the text mentioned in the private defence minutes. We remind you that the time to implement these modifications may not exceed three months of full-time work (à supprimer si pas de modifications nécessaires).</p>
<p>To view the private defence minutes, please click on this link <a href="{parcours_doctoral_link_front_private_defense_minutes}">{parcours_doctoral_link_front_private_defense_minutes}</a>.</p>
<p>Please submit no later than two weeks before the date set for the public defence the final version of your thesis and its distribution arrangements to your lead supervisor for signature via the application <a href="{parcours_doctoral_link_front_thesis_distribution_authorisation}">{parcours_doctoral_link_front_thesis_distribution_authorisation}</a>.</p>
<p>Please contact us should you require further information.</p>
<p>Sincerely,</p>
<p>{sender_name} - {management_entity_name}</p>''',
                'fr-be': '''\
<p>Cher, Chère, Cher.ère {student_first_name} {student_last_name},</p>
<p>A l'issue de votre défense privée, les membres du jury ont jugé votre thèse recevable, moyennant les modifications à apporter au texte mentionnées dans le procès-verbal de défense privée. Nous vous rappelons que la mise en œuvre de ces modifications ne peut excéder trois mois de travail à temps plein. (à supprimer si pas de modifications nécessaires).</p>
<p>Pour visualiser le procès-verbal de défense privée, merci de cliquer sur ce lien <a href="{parcours_doctoral_link_front_private_defense_minutes}">{parcours_doctoral_link_front_private_defense_minutes}</a>.</p>
<p>Au plus tard deux semaines avant la date fixée pour la soutenance publique, veuillez soumettre la version définitive de votre thèse et ses modalités de diffusion à la signature de votre promoteur.trice de référence, via l'application <a href="{parcours_doctoral_link_front_thesis_distribution_authorisation}">{parcours_doctoral_link_front_thesis_distribution_authorisation}</a>.</p>
<p>Nous restons à votre disposition pour tout autre renseignement complémentaire.</p>
<p>Bien cordialement.</p>
<p>---</p>
<p>{sender_name} - {management_entity_name}</p>''',
            },
        ),
        MailTemplateMigration(
            PARCOURS_DOCTORAL_EMAIL_PRIVATE_DEFENSE_ON_REPEAT,
            {
                'en': 'Repeat private thesis defence for {student_first_name} {student_last_name}',
                'fr-be': 'Défense privée à recommencer {student_first_name} {student_last_name}',
            },
            {
                'en': '''\
<p>Dear {student_first_name} {student_last_name},</p>
<p>Following your private defence, the board members have judged your thesis to be inadmissible.</p>
<p>The board authorises you to repeat the private defence within ...</p>
<p>To view the private defence minutes, please click on this link <a href="{parcours_doctoral_link_front_private_defense_minutes}">{parcours_doctoral_link_front_private_defense_minutes}</a>.</p>
<p>Please contact us should you require further information.</p>
<p>Sincerely,</p>
<p>{sender_name} - {management_entity_name}</p>''',
                'fr-be': '''\
<p>Cher, Chère, Cher.ère {student_first_name} {student_last_name},</p>
<p>A l'issue de votre défense privée, les membres du jury ont jugé votre thèse non recevable.</p>
<p>Votre jury de thèse vous autorise à représenter cette épreuve dans un délai de ...</p>
<p>Pour visualiser le procès-verbal de défense privée, merci de cliquer sur ce lien <a href="{parcours_doctoral_link_front_private_defense_minutes}">{parcours_doctoral_link_front_private_defense_minutes}</a>.</p>
<p>Nous restons à votre disposition pour tout autre renseignement complémentaire.</p>
<p>Bien cordialement.</p>
<p>---</p>
<p>{sender_name} - {management_entity_name}</p>''',
            },
        ),
        MailTemplateMigration(
            PARCOURS_DOCTORAL_EMAIL_PRIVATE_DEFENSE_ON_FAILURE,
            {
                'en': 'Failed thesis defence for {student_first_name} {student_last_name}',
                'fr-be': 'Défense privée en échec {student_first_name} {student_last_name}',
            },
            {
                'en': '''\
<p>Dear {student_first_name} {student_last_name},</p>
<p>Following your private defence, the board members have judged your thesis to be inadmissible.</p>
<p>We remind you that the maximum number of private defences is set at two. A third private defence may only be authorised on the basis of a duly substantiated application submitted to the UCLouvain PhD Committee (CODOL) and if justified by exceptional circumstances.</p>
<p>To view the private defence minutes, please click on this link <a href="{parcours_doctoral_link_front_private_defense_minutes}">{parcours_doctoral_link_front_private_defense_minutes}</a></p>
<p>Please contact us should you require further information.</p>
<p>Sincerely,</p>
<p>{sender_name} - {management_entity_name}</p>''',
                'fr-be': '''\
<p>Cher, Chère, Cher.ère {student_first_name} {student_last_name},</p>
<p>À l'issue de votre défense privée, les membres du jury ont jugé votre thèse non recevable.</p>
<p>Nous vous rappelons que le nombre maximal de défenses privées est fixé à deux. Une troisième défense privée ne pourra être autorisée que sur demande dûment motivée auprès de la Commission doctorale de l'UCLouvain (CODOL) et si des circonstances exceptionnelles le justifient.</p>
<p>Pour visualiser le procès-verbal de défense privée, merci de cliquer sur ce lien <a href="{parcours_doctoral_link_front_private_defense_minutes}">{parcours_doctoral_link_front_private_defense_minutes}</a></p>
<p>Nous restons à votre disposition pour tout autre renseignement complémentaire.</p>
<p>Bien cordialement.</p>
<p>---</p>
<p>{sender_name} - {management_entity_name}</p>''',
            },
        ),
    ]
