# Generated by Django 4.2.20 on 2025-09-17 14:55

import osis_document_components.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parcours_doctoral", "0029_alter_parcoursdoctoral_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="parcoursdoctoral",
            name="announcement_photo",
            field=osis_document_components.fields.FileField(
                base_field=models.UUIDField(),
                default=list,
                size=1,
                verbose_name="Photo for announcement",
            ),
        ),
        migrations.AddField(
            model_name="parcoursdoctoral",
            name="announcement_summary",
            field=models.TextField(blank=True, default="", verbose_name="Summary for announcement"),
        ),
        migrations.AddField(
            model_name="parcoursdoctoral",
            name="defense_additional_information",
            field=models.TextField(blank=True, default="", verbose_name="Additional information"),
        ),
        migrations.AddField(
            model_name="parcoursdoctoral",
            name="defense_datetime",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Public defence date and time"),
        ),
        migrations.AddField(
            model_name="parcoursdoctoral",
            name="defense_deliberation_room",
            field=models.TextField(blank=True, default="", verbose_name="Deliberation room"),
        ),
        migrations.AddField(
            model_name="parcoursdoctoral",
            name="defense_minutes",
            field=osis_document_components.fields.FileField(
                base_field=models.UUIDField(),
                default=list,
                size=None,
                verbose_name="Public defence minutes",
            ),
        ),
        migrations.AddField(
            model_name="parcoursdoctoral",
            name="defense_minutes_canvas",
            field=osis_document_components.fields.FileField(
                base_field=models.UUIDField(),
                default=list,
                size=None,
                verbose_name="Public defence minutes canvas",
            ),
        ),
        migrations.AddField(
            model_name="parcoursdoctoral",
            name="defense_place",
            field=models.TextField(blank=True, default="", verbose_name="Public defence location"),
        ),
        migrations.AddField(
            model_name="parcoursdoctoral",
            name="diploma_collection_date",
            field=models.DateField(blank=True, null=True, verbose_name="Diploma collection date"),
        ),
        migrations.AlterField(
            model_name="parcoursdoctoral",
            name="status",
            field=models.CharField(
                choices=[
                    ("ADMIS", "ADMIS"),
                    ("EN_ATTENTE_DE_SIGNATURE", "EN_ATTENTE_DE_SIGNATURE"),
                    ("CONFIRMATION_SOUMISE", "CONFIRMATION_SOUMISE"),
                    ("CONFIRMATION_REUSSIE", "CONFIRMATION_REUSSIE"),
                    ("NON_AUTORISE_A_POURSUIVRE", "NON_AUTORISE_A_POURSUIVRE"),
                    ("CONFIRMATION_A_REPRESENTER", "CONFIRMATION_A_REPRESENTER"),
                    ("JURY_SOUMIS", "JURY_SOUMIS"),
                    ("JURY_APPROUVE_CA", "JURY_APPROUVE_CA"),
                    ("JURY_APPROUVE_CDD", "JURY_APPROUVE_CDD"),
                    ("JURY_REFUSE_CDD", "JURY_REFUSE_CDD"),
                    ("JURY_APPROUVE_ADRE", "JURY_APPROUVE_ADRE"),
                    ("JURY_REFUSE_ADRE", "JURY_REFUSE_ADRE"),
                    ("DEFENSE_PRIVEE_SOUMISE", "DEFENSE_PRIVEE_SOUMISE"),
                    ("DEFENSE_PRIVEE_AUTORISEE", "DEFENSE_PRIVEE_AUTORISEE"),
                    ("DEFENSE_PRIVEE_A_RECOMMENCER", "DEFENSE_PRIVEE_A_RECOMMENCER"),
                    ("DEFENSE_PRIVEE_REUSSIE", "DEFENSE_PRIVEE_REUSSIE"),
                    ("DEFENSE_PRIVEE_EN_ECHEC", "DEFENSE_PRIVEE_EN_ECHEC"),
                    ("SOUTENANCE_PUBLIQUE_SOUMISE", "SOUTENANCE_PUBLIQUE_SOUMISE"),
                    ("SOUTENANCE_PUBLIQUE_AUTORISEE", "SOUTENANCE_PUBLIQUE_AUTORISEE"),
                    ("PROCLAME", "PROCLAME"),
                    ("ABANDON", "ABANDON"),
                ],
                default="ADMIS",
                max_length=64,
                verbose_name="Status",
            ),
        ),
    ]
