# Generated by Django 4.2.20 on 2025-09-09 16:03

from django.db import migrations
from osis_mail_template import MailTemplateMigration

from parcours_doctoral.mail_templates.public_defense import *


class Migration(migrations.Migration):

    dependencies = [
        (
            "parcours_doctoral",
            "0031_parcoursdoctoral_announcement_photo_and_more",
        ),
    ]

    operations = [
        MailTemplateMigration(
            PARCOURS_DOCTORAL_EMAIL_PUBLIC_DEFENSE_AUTHORISATION,
            {
                'en': 'Public defence authorisation for {student_first_name} {student_last_name}',
                'fr-be': 'Soutenance publique autorisée {student_first_name} {student_last_name}',
            },
            {
                'en': '''\
<p>Dear {student_first_name} {student_last_name},</p>
<p>The PhD Field Committee takes note that the public defence for your {training_title} will take place on {public_defense_date}.</p>
<p>Please note that the Doctoral Regulations stipulate that at least half of the board members must actively participate in the public thesis defence.</p>
<p>Members who are not present should send a written report to the chair before the session, giving reasons for their opinion based on the quality of the thesis and listing the questions they would like to ask the candidate.</p>
<p>Please contact us should you require further information.</p>
<p>Sincerely,</p>
<p>{sender_name} - {management_entity_name}</p>''',
                'fr-be': '''\
<p>Cher, Chère, Cher.ère {student_first_name} {student_last_name},</p>
<p>La Commission doctorale de votre domaine prend note que votre soutenance publique pour votre {training_title} aura lieu le {public_defense_date}.</p>
<p>Nous vous rappelons qu’il est prévu dans le Règlement doctoral que la moitié au moins des membres du jury participe activement à la soutenance publique de la thèse.</p>
<p>Les membres absent·es font parvenir au/à la président·e, avant la séance, un rapport écrit avec un avis motivé sur la valeur de la thèse et l’inventaire des questions qu’ils/elles souhaitent poser au candidat.</p>
<p>Nous restons à votre disposition pour tout autre renseignement complémentaire.</p>
<p>Bien cordialement.</p>
<p>---</p>
<p>{sender_name} - {management_entity_name}</p>''',
            },
        ),
        MailTemplateMigration(
            PARCOURS_DOCTORAL_EMAIL_PUBLIC_DEFENSE_JURY_INVITATION,
            {
                'en': 'Public defence invitation for {student_first_name} {student_last_name}',
                'fr-be': 'Convocation soutenance publique {student_first_name} {student_last_name}',
            },
            {
                'en': '''\
<p>Dear {jury_member_first_name} {jury_member_last_name},</p>
<p>{student_first_name} {student_last_name} will present the public defence for {training_title} on {public_defense_date} in room {public_defense_place}.</p>
<p>Prior to the public defence, the board will meet in room {deliberation_room}.</p>
<p>Further details will be sent to you at a later date concerning your reception and the day's practical organisation.</p>
<p>Thank you in advance for your important contribution.</p>
<p>Please contact me should you require further information.</p>
<p>Sincerely,</p>
<p>{sender_name} - {management_entity_name}</p>''',
                'fr-be': '''\
<p>Cher, Chère, Cher.ère {jury_member_first_name} {jury_member_last_name},</p>
<p>{student_first_name} {student_last_name} présentera sa soutenance publique pour son {training_title} le {public_defense_date}, dans le local {public_defense_place}.</p>
<p>Préalablement à la soutenance publique, le jury se réunira au local {deliberation_room}.</p>
<p>De plus amples détails vous parviendront ultérieurement concernant votre accueil et l'organisation pratique de cette journée.</p>
<p>En vous remerciant d'avance pour votre contribution importante, je vous adresse mes plus cordiales
salutations et reste bien entendu à votre entière disposition.</p>
<p>---</p>
<p>{sender_name} - {management_entity_name}</p>''',
            },
        ),
        MailTemplateMigration(
            PARCOURS_DOCTORAL_EMAIL_PUBLIC_DEFENSE_ON_SUCCESS,
            {
                'en': 'Obtention du grade de doctorat',
                'fr-be': 'PhD awarded',
            },
            {
                'en': '''\
<p>Dear {student_first_name} {student_last_name},</p>
<p>Congratulations on earning your PhD.</p>
<p>To view the minutes of your public defence, please click on this link <a href="{parcours_doctoral_link_front_public_defense_minutes}">{parcours_doctoral_link_front_public_defense_minutes}</a>.</p>
<p>We will contact you when your diploma is available for collection.</p>
<p>Please contact us should you require further information.</p>
<p>Sincerely,</p>
<p>{sender_name} - {management_entity_name}</p>''',
                'fr-be': '''\
<p>Cher, Chère, Cher.ère {student_first_name} {student_last_name},</p>
<p>Nous tenons à vous féliciter pour l’obtention de votre grade de doctorat.</p>
<p>Pour visualiser le procès-verbal de votre soutenance publique, merci de cliquer sur ce lien <a href="{parcours_doctoral_link_front_public_defense_minutes}">{parcours_doctoral_link_front_public_defense_minutes}</a>.</p>
<p>Nous vous recontacterons lorsque votre diplôme sera disponible pour retrait.</p>
<p>Nous restons à votre disposition pour tout autre renseignement complémentaire.</p>
<p>Bien cordialement.</p>
<p>---</p>
<p>{sender_name} - {management_entity_name}</p>''',
            },
        ),
    ]
