# Generated by Django 4.2.20 on 2025-09-22 16:53

import osis_mail_template.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parcours_doctoral", "0032_alter_parcoursdoctoral_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cddmailtemplate",
            name="identifier",
            field=models.CharField(
                choices=[
                    (
                        "osis-parcours-doctoral-generic",
                        "osis-parcours-doctoral-generic",
                    ),
                    (
                        "osis-parcours-doctoral-confirmation-info-student",
                        "osis-parcours-doctoral-confirmation-info-student",
                    ),
                    (
                        "osis-parcours-doctoral-confirmation-on-failure-student",
                        "osis-parcours-doctoral-confirmation-on-failure-student",
                    ),
                    (
                        "osis-parcours-doctoral-confirmation-on-retaking-student",
                        "osis-parcours-doctoral-confirmation-on-retaking-student",
                    ),
                    (
                        "osis-parcours-doctoral-private-defense-jury-invitation",
                        "osis-parcours-doctoral-private-defense-jury-invitation",
                    ),
                    (
                        "osis-parcours-doctoral-private-defense-on-success",
                        "osis-parcours-doctoral-private-defense-on-success",
                    ),
                    (
                        "osis-parcours-doctoral-private-defense-on-repeat",
                        "osis-parcours-doctoral-private-defense-on-repeat",
                    ),
                    (
                        "osis-parcours-doctoral-private-defense-on-failure",
                        "osis-parcours-doctoral-private-defense-on-failure",
                    ),
                    (
                        "osis-parcours-doctoral-public-defense-jury-invitation",
                        "osis-parcours-doctoral-public-defense-jury-invitation",
                    ),
                    (
                        "osis-parcours-doctoral-public-defense-authorisation",
                        "osis-parcours-doctoral-public-defense-authorisation",
                    ),
                    (
                        "osis-parcours-doctoral-public-defense-on-success",
                        "osis-parcours-doctoral-public-defense-on-success",
                    ),
                ],
                max_length=255,
                validators=[osis_mail_template.models.check_mail_template_identifier],
                verbose_name="Identifier",
            ),
        ),
    ]
