# Generated by Django 4.2.24 on 2025-10-08 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0717_update_dates_calendrier_academique"),
        ("parcours_doctoral", "0035_public_defense_mail_templates"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScebManager",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "visible",
                    models.BooleanField(
                        default=True,
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="base.person",
                    ),
                ),
            ],
            options={
                "verbose_name": "Role: SCEB manager",
                "verbose_name_plural": "Role: SCEB managers",
            },
        ),
        migrations.AddConstraint(
            model_name="scebmanager",
            constraint=models.UniqueConstraint(
                fields=("person",),
                name="unique_sceb_manager",
            ),
        ),
    ]
