# Generated by Django 4.2.25 on 2025-11-18 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parcours_doctoral", "0036_scebmanager"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parcoursdoctoral",
            name="cotutelle_motivation",
            field=models.CharField(blank=True, default="", max_length=1024, verbose_name="Motivation"),
        ),
    ]
