# Generated by Django 5.2.8 on 2025-12-05 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("parcours_doctoral", "0037_alter_parcoursdoctoral_cotutelle_motivation"),
        (
            "parcours_doctoral",
            "0037_remove_the_private_defenses_related_to_pre_admission",
        ),
    ]

    operations = []
