# Generated by Django 4.2.20 on 2025-09-09 16:03

from django.db import migrations
from osis_mail_template import MailTemplateMigration

from parcours_doctoral.mail_templates.admissibility import *


class Migration(migrations.Migration):

    dependencies = [
        (
            "parcours_doctoral",
            "0037_alter_cddmailtemplate_identifier_and_more",
        ),
    ]

    operations = [
        MailTemplateMigration(
            PARCOURS_DOCTORAL_EMAIL_ADMISSIBILITY_JURY_INVITATION,
            {
                'en': 'Admissibility decision for {student_first_name} {student_last_name}',
                'fr-be': 'Décision de recevabilité {student_first_name} {student_last_name}',
            },
            {
                'en': '''\
<p>Dear {jury_member_first_name} {jury_member_last_name},</p>
<p>{student_first_name} {student_last_name}'s  thesis has just been distributed to you for an admissibility decision
for {training_title}.</p>
<p>We remind you that, as a board member, you must give your opinion on the thesis by {admissibility_decision_date}.</p>
<p>Thank you in advance for your important contribution.</p>
<p>Please contact me should you require further information.</p>
<p>Sincerely,</p>
<p>---</p>
<p>{jury_president}<br>Board Chair<br>{jury_secretary}<br>Board Secretary</p>''',
                'fr-be': '''\
<p>Cher, Chère, Cher.ère {jury_member_first_name} {jury_member_last_name},</p>
<p>Le texte de la thèse de {student_first_name} {student_last_name} vient de vous être distribué en vue de la décision
de recevabilité, pour son {training_title}.</p>
<p>Nous vous rappelons qu'en tant que membre du jury, vous devez communiquer votre avis sur la thèse pour le
{admissibility_decision_date}.</p>
<p>En vous remerciant d'avance pour votre contribution importante, je vous adresse mes plus cordiales
salutations et reste bien entendu à votre entière disposition.</p>
<p>---</p>
<p>{jury_president}<br>Président.e du jury<br>{jury_secretary}<br>Secrétaire du jury</p>''',
            },
        ),
        MailTemplateMigration(
            PARCOURS_DOCTORAL_EMAIL_ADMISSIBILITY_ON_SUCCESS,
            {
                'en': "{student_first_name} {student_last_name}'s thesis is admissible",
                'fr-be': 'Thèse recevable {student_first_name} {student_last_name}',
            },
            {
                'en': '''\
<p>Dear board members and {student_first_name} {student_last_name},</p>
<p>After consultation, we are pleased to inform you that the board has issued a favourable opinion and considers
{student_first_name} {student_last_name}'s thesis to be admissible as it stands/subject to the modifications to be
made to the text mentioned in the admissibility report <i>(supprimer si pas de modifications)</i>.</p>
<p>The time to implement these modifications may not exceed three months of full-time work <i>(supprimer si pas de modifications)</i>.</p>
<p>To view the admissibility report, please click on this link <a href="{parcours_doctoral_link_front_admissibility_minutes}">{parcours_doctoral_link_front_admissibility_minutes}</a>.</p>
<p>We invite the PhD student to submit no later than two weeks before the date set for the public defence the final version of the thesis and its distribution arrangements for signature by the lead supervisor via the application <a href="{parcours_doctoral_link_front_thesis_distribution_authorisation}">{parcours_doctoral_link_front_thesis_distribution_authorisation}</a>.</p>
<p>Please contact us should you require further information.</p>
<p>Sincerely,</p>
<p>---</p>
<p>{jury_president}<br>Board Chair<br>{jury_secretary}<br>Board Secretary</p>''',
                'fr-be': '''\
<p>Chers, Chères, Cher.ères membres du jury,</p>
<p>Cher, Chère, Cher.ère, {student_first_name} {student_last_name},</p>
<p>Après consultation, nous avons le plaisir de vous informer que le jury a émis un avis favorable et juge la thèse de {student_first_name} {student_last_name} recevable en l'état / moyennant les modifications à apporter au texte mentionnées dans le procès-verbal de recevabilité <i>(supprimer si pas de modifications)</i>.</p>
<p>La mise en œuvre de ces modifications ne peut excéder trois mois de travail à temps plein <i>(supprimer si pas de modifications)</i>.</p>
<p>Pour visualiser le procès-verbal de recevabilité, merci de cliquer sur ce lien <a href="{parcours_doctoral_link_front_admissibility_minutes}">{parcours_doctoral_link_front_admissibility_minutes}</a>.</p>
<p>Nous invitons {student_reference} à soumettre, au plus tard deux semaines avant la date fixée pour la soutenance publique, la version définitive de sa thèse et ses modalités de diffusion à la signature du/de la promoteur.trice de référence, via l'application <a href="{parcours_doctoral_link_front_thesis_distribution_authorisation}">{parcours_doctoral_link_front_thesis_distribution_authorisation}</a>.</p>
<p>Nous restons à votre disposition pour tout autre renseignement complémentaire.</p>
<p>Bien cordialement.</p>
<p>---</p>
<p>{jury_president}<br>Président.e du jury<br>{jury_secretary}<br>Secrétaire du jury</p>''',
            },
        ),
        MailTemplateMigration(
            PARCOURS_DOCTORAL_EMAIL_ADMISSIBILITY_ON_REPEAT,
            {
                'en': 'Repeat admissibility review for {student_first_name} {student_last_name}',
                'fr-be': 'Recevabilité à recommencer {student_first_name} {student_last_name}',
            },
            {
                'en': '''\
<p>Dear board members and {student_first_name} {student_last_name},</p>
<p>After consultation, we inform you that the board has judged {student_first_name} {student_last_name}’s thesis to be inadmissible but authorises the submission of a revised version within ...</p>
<p>To view the minutes, please click on this link <a href="{parcours_doctoral_link_front_admissibility_minutes}">{parcours_doctoral_link_front_admissibility_minutes}</a>.</p>
<p>Please contact us should you require further information.</p>
<p>Sincerely,</p>
<p>---</p>
<p>{jury_president}<br>Board Chair<br>{jury_secretary}<br>Board Secretary</p>''',
                'fr-be': '''\
<p>Chers, Chères, Cher.ères membres du jury,</p>
<p>Cher, Chère, Cher.ère, {student_first_name} {student_last_name},</p>
<p>Après consultation, nous vous informons que le jury a jugé la thèse de {student_first_name} {student_last_name} non recevable, mais l’autorise à soumettre une version révisée de celle-ci, dans un délai de ...</p>
<p>Pour visualiser le procès-verbal de défense privée, merci de cliquer sur ce lien <a href="{parcours_doctoral_link_front_admissibility_minutes}">{parcours_doctoral_link_front_admissibility_minutes}</a>.</p>
<p>Nous restons à votre disposition pour tout autre renseignement complémentaire.</p>
<p>Bien cordialement.</p>
<p>---</p>
<p>{jury_president}<br>Président.e du jury<br>{jury_secretary}<br>Secrétaire du jury</p>''',
            },
        ),
        MailTemplateMigration(
            PARCOURS_DOCTORAL_EMAIL_ADMISSIBILITY_ON_FAILURE,
            {
                'en': "{student_first_name} {student_last_name}'s thesis is inadmissible",
                'fr-be': 'Recevabilité en échec {student_first_name} {student_last_name}',
            },
            {
                'en': '''\
<p>Dear board members and {student_first_name} {student_last_name},</p>
<p>After a second consultation, we inform you that the board has judged {student_first_name} {student_last_name}'s thesis to be inadmissible and can no longer consider it.</p>
<p>To view the admissibility minutes, please click on this link <a href="{parcours_doctoral_link_front_admissibility_minutes}">{parcours_doctoral_link_front_admissibility_minutes}</a></p>
<p>Please contact us should you require further information.</p>
<p>Sincerely,</p>
<p>---</p>
<p>{jury_president}<br>Board Chair<br>{jury_secretary}<br>Board Secretary</p>''',
                'fr-be': '''\
<p>Chers, Chères, Cher.ères membres du jury,</p>
<p>Cher, Chère, Cher.ère, {student_first_name} {student_last_name},</p>
<p>Après une seconde consultation, nous vous informons que le jury a jugé la thèse de {student_first_name} {student_last_name} non recevable et qu’{student_personal_pronoun} n’est plus dans les conditions de pouvoir la représenter.</p>
<p>Pour visualiser le procès-verbal de recevabilité, merci de cliquer sur ce lien <a href="{parcours_doctoral_link_front_admissibility_minutes}">{parcours_doctoral_link_front_admissibility_minutes}</a></p>
<p>Nous restons à votre disposition pour tout autre renseignement complémentaire.</p>
<p>Bien cordialement.</p>
<p>---</p>
<p>{jury_president}<br>Président.e du jury<br>{jury_secretary}<br>Secrétaire du jury</p>''',
            },
        ),
    ]
