# Generated by Django 4.2.25 on 2025-10-28 15:50

import uuid

import django.db.models.deletion
import osis_document_components.fields
import osis_mail_template.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parcours_doctoral", "0037_admissibility_mail_templates"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cddmailtemplate",
            name="identifier",
            field=models.CharField(
                choices=[
                    (
                        "osis-parcours-doctoral-generic",
                        "osis-parcours-doctoral-generic",
                    ),
                    (
                        "osis-parcours-doctoral-confirmation-info-student",
                        "osis-parcours-doctoral-confirmation-info-student",
                    ),
                    (
                        "osis-parcours-doctoral-confirmation-on-failure-student",
                        "osis-parcours-doctoral-confirmation-on-failure-student",
                    ),
                    (
                        "osis-parcours-doctoral-confirmation-on-retaking-student",
                        "osis-parcours-doctoral-confirmation-on-retaking-student",
                    ),
                    (
                        "osis-parcours-doctoral-admissibility-jury-invitation",
                        "osis-parcours-doctoral-admissibility-jury-invitation",
                    ),
                    (
                        "osis-parcours-doctoral-admissibility-on-success",
                        "osis-parcours-doctoral-admissibility-on-success",
                    ),
                    (
                        "osis-parcours-doctoral-admissibility-on-repeat",
                        "osis-parcours-doctoral-admissibility-on-repeat",
                    ),
                    (
                        "osis-parcours-doctoral-admissibility-on-failure",
                        "osis-parcours-doctoral-admissibility-on-failure",
                    ),
                    (
                        "osis-parcours-doctoral-private-defense-jury-invitation",
                        "osis-parcours-doctoral-private-defense-jury-invitation",
                    ),
                    (
                        "osis-parcours-doctoral-private-defense-on-success",
                        "osis-parcours-doctoral-private-defense-on-success",
                    ),
                    (
                        "osis-parcours-doctoral-private-defense-on-repeat",
                        "osis-parcours-doctoral-private-defense-on-repeat",
                    ),
                    (
                        "osis-parcours-doctoral-private-defense-on-failure",
                        "osis-parcours-doctoral-private-defense-on-failure",
                    ),
                    (
                        "osis-parcours-doctoral-public-defense-jury-invitation",
                        "osis-parcours-doctoral-public-defense-jury-invitation",
                    ),
                    (
                        "osis-parcours-doctoral-public-defense-authorisation",
                        "osis-parcours-doctoral-public-defense-authorisation",
                    ),
                    (
                        "osis-parcours-doctoral-public-defense-on-success",
                        "osis-parcours-doctoral-public-defense-on-success",
                    ),
                ],
                max_length=255,
                validators=[osis_mail_template.models.check_mail_template_identifier],
                verbose_name="Identifier",
            ),
        ),
        migrations.AlterField(
            model_name="parcoursdoctoral",
            name="status",
            field=models.CharField(
                choices=[
                    ("ADMIS", "ADMIS"),
                    ("EN_ATTENTE_DE_SIGNATURE", "EN_ATTENTE_DE_SIGNATURE"),
                    ("CONFIRMATION_SOUMISE", "CONFIRMATION_SOUMISE"),
                    ("CONFIRMATION_REUSSIE", "CONFIRMATION_REUSSIE"),
                    ("NON_AUTORISE_A_POURSUIVRE", "NON_AUTORISE_A_POURSUIVRE"),
                    ("CONFIRMATION_A_REPRESENTER", "CONFIRMATION_A_REPRESENTER"),
                    ("JURY_SOUMIS", "JURY_SOUMIS"),
                    ("JURY_APPROUVE_CA", "JURY_APPROUVE_CA"),
                    ("JURY_APPROUVE_CDD", "JURY_APPROUVE_CDD"),
                    ("JURY_REFUSE_CDD", "JURY_REFUSE_CDD"),
                    ("JURY_APPROUVE_ADRE", "JURY_APPROUVE_ADRE"),
                    ("JURY_REFUSE_ADRE", "JURY_REFUSE_ADRE"),
                    ("RECEVABILITE_SOUMISE", "RECEVABILITE_SOUMISE"),
                    ("RECEVABILITE_A_RECOMMENCER", "RECEVABILITE_A_RECOMMENCER"),
                    ("RECEVABILITE_REUSSIE", "RECEVABILITE_REUSSIE"),
                    ("RECEVABILITE_EN_ECHEC", "RECEVABILITE_EN_ECHEC"),
                    ("DEFENSE_PRIVEE_SOUMISE", "DEFENSE_PRIVEE_SOUMISE"),
                    ("DEFENSE_PRIVEE_AUTORISEE", "DEFENSE_PRIVEE_AUTORISEE"),
                    ("DEFENSE_PRIVEE_A_RECOMMENCER", "DEFENSE_PRIVEE_A_RECOMMENCER"),
                    ("DEFENSE_PRIVEE_REUSSIE", "DEFENSE_PRIVEE_REUSSIE"),
                    ("DEFENSE_PRIVEE_EN_ECHEC", "DEFENSE_PRIVEE_EN_ECHEC"),
                    ("SOUTENANCE_PUBLIQUE_SOUMISE", "SOUTENANCE_PUBLIQUE_SOUMISE"),
                    ("SOUTENANCE_PUBLIQUE_AUTORISEE", "SOUTENANCE_PUBLIQUE_AUTORISEE"),
                    ("PROCLAME", "PROCLAME"),
                    ("ABANDON", "ABANDON"),
                ],
                default="ADMIS",
                max_length=64,
                verbose_name="Status",
            ),
        ),
        migrations.CreateModel(
            name="Admissibility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "decision_date",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Date of admissibility decision",
                    ),
                ),
                (
                    "manuscript_submission_date",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Date of manuscript submission to the thesis exam board",
                    ),
                ),
                (
                    "thesis_exam_board_opinion",
                    osis_document_components.fields.FileField(
                        base_field=models.UUIDField(),
                        default=list,
                        size=None,
                        verbose_name="Thesis exam board opinion",
                    ),
                ),
                (
                    "minutes",
                    osis_document_components.fields.FileField(
                        base_field=models.UUIDField(),
                        default=list,
                        size=None,
                        verbose_name="Admissibility minutes",
                    ),
                ),
                (
                    "minutes_canvas",
                    osis_document_components.fields.FileField(
                        base_field=models.UUIDField(),
                        default=list,
                        size=None,
                        verbose_name="Admissibility minutes canvas",
                    ),
                ),
                (
                    "current_parcours_doctoral",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="current_admissibility",
                        to="parcours_doctoral.parcoursdoctoral",
                        verbose_name="Doctorate whose this admissibility is the active one",
                    ),
                ),
                (
                    "parcours_doctoral",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="parcours_doctoral.parcoursdoctoral",
                        verbose_name="Doctorate",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
