# Generated by Django 4.2.25 on 2025-11-04 12:32

import django.contrib.postgres.fields
import django.db.models.deletion
import osis_signature.contrib.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("osis_signature", "0003_external_actor"),
        ("parcours_doctoral", "0038_admissibility_mail_templates"),
    ]

    operations = [
        migrations.CreateModel(
            name="ThesisDistributionAuthorizationActor",
            fields=[
                (
                    "actor_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="osis_signature.actor",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("PROMOTEUR", "Supervisor"), ("SCEB", "SCEB"), ("ADRE", "ADRE")],
                        max_length=50,
                        verbose_name="Role",
                    ),
                ),
                (
                    "internal_comment",
                    models.TextField(blank=True, default="", verbose_name="Internal comment"),
                ),
                (
                    "rejection_reason",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=50,
                        verbose_name="Grounds for denied",
                    ),
                ),
            ],
            bases=("osis_signature.actor",),
        ),
        migrations.CreateModel(
            name="ThesisDistributionAuthorization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DIFFUSION_NON_SOUMISE", "Not submitted distribution"),
                            ("DIFFUSION_SOUMISE", "Submitted distribution"),
                            (
                                "DIFFUSION_VALIDEE_PROMOTEUR",
                                "Distribution validated by the supervisor",
                            ),
                            (
                                "DIFFUSION_REFUSEE_PROMOTEUR",
                                "Distribution refused by the supervisor",
                            ),
                            (
                                "DIFFUSION_VALIDEE_ADRE",
                                "Distribution validated by ADRE",
                            ),
                            ("DIFFUSION_REFUSEE_ADRE", "Distribution refused by ADRE"),
                            (
                                "DIFFUSION_VALIDEE_SCEB",
                                "Distribution validated by SCEB",
                            ),
                            ("DIFFUSION_REFUSEE_SCEB", "Distribution refused by SCEB"),
                        ],
                        default="DIFFUSION_NON_SOUMISE",
                        max_length=30,
                        verbose_name="Status",
                    ),
                ),
                (
                    "funding_sources",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="Sources of funding throughout PhD",
                    ),
                ),
                (
                    "thesis_summary_in_english",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="Summary in English",
                    ),
                ),
                (
                    "thesis_summary_in_other_language",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="Summary in other language",
                    ),
                ),
                (
                    "thesis_keywords",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=50),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "conditions",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ACCES_LIBRE", "Free access (Internet)"),
                            ("ACCES_RESTREINT", "Limited access (Intranet)"),
                            ("ACCES_INTERDIT", "Forbidden access"),
                            ("ACCES_EMBARGO", "Embargo access"),
                        ],
                        default="",
                        max_length=30,
                        verbose_name="Conditions",
                    ),
                ),
                (
                    "embargo_date",
                    models.DateField(blank=True, null=True, verbose_name="Embargo date"),
                ),
                (
                    "additional_limitation_for_specific_chapters",
                    models.TextField(
                        blank=True,
                        default="",
                        verbose_name="Additional limitation for certain specific chapters",
                    ),
                ),
                (
                    "accepted_on",
                    models.DateField(blank=True, null=True, verbose_name="Acceptation date"),
                ),
                (
                    "acceptation_content",
                    models.TextField(blank=True, default="", verbose_name="Acceptation content"),
                ),
                (
                    "signature_group",
                    osis_signature.contrib.fields.SignatureProcessField(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="osis_signature.process",
                    ),
                ),
                (
                    "parcours_doctoral",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="parcours_doctoral.parcoursdoctoral",
                        verbose_name="Doctorate",
                        related_name='thesis_distribution_authorization',
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="parcoursdoctoral",
            name="jury_group",
            field=osis_signature.contrib.fields.SignatureProcessField(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="doctorate_from_jury_group",
                to="osis_signature.process",
            ),
        ),
    ]
