# Generated by Django 4.2.20 on 2025-09-09 16:03

from django.db import migrations
from osis_mail_template import MailTemplateMigration

from parcours_doctoral.mail_templates.thesis_distribution_authorization import *


class Migration(migrations.Migration):

    dependencies = [
        (
            "parcours_doctoral",
            "0039_thesisdistributionauthorizationactor_and_more",
        ),
    ]

    operations = [
        MailTemplateMigration(
            PARCOURS_DOCTORAL_EMAIL_THESIS_DISTRIBUTION_AUTHORIZATION_PROMOTER_INVITATION,
            {
                'en': "Invitation to authorise distribution of {student_last_name} {student_last_name}'s thesis for {training_title}",
                'fr-be': "Invitation à autoriser la diffusion de la thèse de {student_last_name} {student_last_name} pour un {training_title}",
            },
            {
                'en': '''\
<p>Professor {promoter_name},</p>
<p>{student_first_name} {student_last_name} has sent you the final version of the thesis for {training_title} and has agreed to the distribution arrangements.</p>
<p>Please indicate your approval or refusal of the <u>final version</u> of the thesis and its <u>distribution arrangements</u> by clicking on this link <a href="{thesis_distribution_authorization_form_front_link}">{thesis_distribution_authorization_form_front_link}</a>.</p>
<p>If the thesis has been produced under joint supervision, you are signing in the name of said joint supervision.</p>
<p>Please contact us should you require further information.</p>
<p>Sincerely,</p>
<p>---</p>
<p>{cdd_manager_names} {doctoral_commission}</p>''',
                'fr-be': '''\
<p>Professeur.e, {promoter_name},</p>
<p>{student_first_name} {student_last_name} vous a transmis la version définitive de sa thèse pour son {training_title} et a fixé avec vous ses modalités de diffusion.</p>
<p>Veuillez indiquer votre approbation ou refus sur la <u>version finalisée</u> de la thèse et ses <u>modalités de diffusion</u> en cliquant sur ce lien <a href="{thesis_distribution_authorization_form_front_link}">{thesis_distribution_authorization_form_front_link}</a>.</p>
<p>Dans le cas où la thèse a été réalisée en copromotion, vous signez pour l'ensemble de la promotion.</p>
<p>Nous restons à votre disposition pour tout autre renseignement complémentaire.</p>
<p>Bien cordialement.</p>
<p>---</p>
<p>{cdd_manager_names} {doctoral_commission}</p>''',
            },
        ),
        MailTemplateMigration(
            PARCOURS_DOCTORAL_EMAIL_THESIS_DISTRIBUTION_AUTHORIZATION_PROMOTER_INVITATION_CONFIRMATION,
            {
                'en': "Invitation to upload electronic version of {student_last_name} {student_last_name}'s thesis for {training_title}",
                'fr-be': "Invitation à téléverser la version électronique de la thèse de {student_last_name} {student_last_name} pour un {training_title}",
            },
            {
                'en': '''\
<p>Dear {student_first_name} {student_last_name},</p>
<p>Please upload an electronic copy of your thesis to the Service Central des Bibliothèques (Central Library Service) no later than two weeks before the date set for the public defence via this link <a href="{dial_link}">{dial_link}</a>.</p>
<p>Please contact us should you require further information.</p>
<p>Sincerely,</p>
<p>---</p>
<p>{cdd_manager_names} {doctoral_commission}</p>''',
                'fr-be': '''\
<p>Cher, Chère, Cher.ère {student_first_name} {student_last_name},</p>
<p>Veuillez téléverser un exemplaire électronique de votre thèse au Service Central des Bibliothèques, au plus tard 2 semaines avant la date fixée pour la soutenance publique,via ce lien <a href="{dial_link}">{dial_link}</a>.</p>
<p>Nous restons à votre disposition pour tout autre renseignement complémentaire.</p>
<p>Bien cordialement.</p>
<p>---</p>
<p>{cdd_manager_names} {doctoral_commission}</p>''',
            },
        ),
        MailTemplateMigration(
            PARCOURS_DOCTORAL_EMAIL_THESIS_DISTRIBUTION_AUTHORIZATION_PROMOTER_REFUSAL,
            {
                'en': "Refusal to distribute electronic version of {student_last_name} {student_last_name}'s thesis for {training_title}",
                'fr-be': "Refus de l’autorisation de diffusion de thèse de {student_last_name} {student_last_name} pour un {training_title}",
            },
            {
                'en': '''\
<p>Dear {student_first_name} {student_last_name},</p>
<p>Professor {promoter_name} (support committee member) has refused the final version of your thesis and/or its distribution arrangements for the following reason: {promoter_refusal_reason}.</p>
<p>Please resubmit your file via your virtual office.</p>
<p>Thank you in advance for your important contribution.</p>
<p>Please contact us should you require further information.</p>
<p>Sincerely,</p>
<p>---</p>
<p>{cdd_manager_names} {doctoral_commission}</p>''',
                'fr-be': '''\
<p>Cher, Chère, Cher.ère, {student_first_name} {student_last_name},</p>
<p>{promoter_title_uppercase} {promoter_name} (membre du comité d’accompagnement) a refusé la version finale de votre thèse et/ou ses modalités de diffusion, pour le motif suivant : {promoter_refusal_reason}.</p>
<p>Nous vous invitons à resoumettre votre dossier via votre bureau virtuel.</p>
<p>Nous restons à votre disposition pour tout autre renseignement complémentaire.</p>
<p>Bien cordialement.</p>
<p>---</p>
<p>{cdd_manager_names} {doctoral_commission}</p>''',
            },
        ),
        MailTemplateMigration(
            PARCOURS_DOCTORAL_EMAIL_THESIS_DISTRIBUTION_AUTHORIZATION_PROMOTER_APPROVAL,
            {
                'en': "Authorisation to distribute {student_last_name} {student_last_name}'s thesis for {training_title}",
                'fr-be': "Autorisation de diffusion de thèse de {student_last_name} {student_last_name} pour un {training_title}",
            },
            {
                'en': '''\
<p>Dear colleague,</p>
<p>The final version of {student_first_name} {student_last_name}’s thesis and its distribution arrangements have been approved by Professor {promoter_name}.</p>
<p>Here is the link to the file <a href="{parcours_doctoral_link_back}">{parcours_doctoral_link_back}</a></p>
<p>Please contact us should you require further information.</p>
<p>Sincerely,</p>
<p>---</p>
<p>{cdd_manager_names} {doctoral_commission}</p>''',
                'fr-be': '''\
<p>Cher, Chère, Cher.ère collègue,</p>
<p>La version finale de thèse de {student_first_name} {student_last_name}, ainsi que ses modalités de diffusion ont été approuvées par {promoter_title_lowercase} {promoter_name}.</p>
<p>Voici le lien vers le dossier <a href="{parcours_doctoral_link_back}">{parcours_doctoral_link_back}</a></p>
<p>Nous restons à votre disposition pour tout autre renseignement complémentaire.</p>
<p>Bien cordialement.</p>
<p>---</p>
<p>{cdd_manager_names} {doctoral_commission}</p>''',
            },
        ),
        MailTemplateMigration(
            PARCOURS_DOCTORAL_EMAIL_THESIS_DISTRIBUTION_AUTHORIZATION_ADRE_REFUSAL,
            {
                'en': "Refusal to distribute {student_last_name} {student_last_name}'s thesis for {training_title}",
                'fr-be': "Refus de diffusion de thèse de {student_last_name} {student_last_name} pour un {training_title}",
            },
            {
                'en': '''\
<p>Dear {student_last_name} {student_last_name},</p>
<p>The Research Administration Department has refused your thesis distribution arrangements for the following reason: {adre_refusal_reason}.</p>
<p>Please resubmit your file via your virtual office.</p>
<p>Please contact us should you require further information.</p>
<p>Sincerely,</p>
<p>---</p>
<p>{adre_manager_name}</p>''',
                'fr-be': '''\
<p>Cher, Chère, Cher.ère {student_last_name} {student_last_name},</p>
<p>Le Service central des bibliothèques a refusé les modalités de diffusion de votre thèse, pour le motif suivant : {adre_refusal_reason}.</p>
<p>Nous vous invitons à resoumettre votre dossier via votre bureau virtuel.</p>
<p>Nous restons à votre disposition pour tout autre renseignement complémentaire.</p>
<p>Bien cordialement.</p>
<p>---</p>
<p>{adre_manager_name}</p>''',
            },
        ),
        MailTemplateMigration(
            PARCOURS_DOCTORAL_EMAIL_THESIS_DISTRIBUTION_AUTHORIZATION_ADRE_APPROVAL,
            {
                'en': "Authorisation to distribute {student_last_name} {student_last_name}'s thesis for {training_title}",
                'fr-be': "Autorisation de diffusion de thèse de {student_last_name} {student_last_name} pour un {training_title}",
            },
            {
                'en': '''\
<p>Dear colleague,</p>
<p>ADRE has approved the thesis distribution arrangements for {student_first_name} {student_last_name}.</p>
<p>Here is the link to the file <a href="{parcours_doctoral_link_back}">{parcours_doctoral_link_back}</a></p>
<p>Please contact us should you require further information.</p>
<p>Sincerely,</p>
<p>---</p>
<p>{adre_manager_name}</p>''',
                'fr-be': '''\
<p>Cher, Chère, Cher.ère collègue,</p>
<p>Les modalités de diffusion de thèse de {student_first_name} {student_last_name} ont été approuvées par ADRE.</p>
<p>Voici le lien vers le dossier <a href="{parcours_doctoral_link_back}">{parcours_doctoral_link_back}</a></p>
<p>Nous restons à votre disposition pour tout autre renseignement complémentaire.</p>
<p>Bien cordialement.</p>
<p>---</p>
<p>{adre_manager_name}</p>''',
            },
        ),
        MailTemplateMigration(
            PARCOURS_DOCTORAL_EMAIL_THESIS_DISTRIBUTION_AUTHORIZATION_SCEB_REFUSAL,
            {
                'en': "Refusal to distribute {student_last_name} {student_last_name}'s thesis for {training_title}",
                'fr-be': "Refus de diffusion de thèse de {student_last_name} {student_last_name} pour un {training_title}",
            },
            {
                'en': '''\
<p>Dear {student_first_name} {student_last_name},</p>
<p>The Service Central des Bibliothèques (Central Library Service) has refused your thesis distribution arrangements for the following reason: {sceb_refusal_reason}.</p>
<p>Please resubmit your file via your virtual office.</p>
<p>Please contact us should you require further information.</p>
<p>Sincerely,</p>
<p>---</p>
<p>{sceb_manager_name}</p>''',
                'fr-be': '''\
<p>Cher, Chère, Cher.ère {student_first_name} {student_last_name},</p>
<p>Le Service central des bibliothèques a refusé les modalités de diffusion de votre thèse, pour le motif suivant : {sceb_refusal_reason}.</p>
<p>Nous vous invitons à resoumettre votre dossier via votre bureau virtuel.</p>
<p>Nous restons à votre disposition pour tout autre renseignement complémentaire.</p>
<p>Bien cordialement.</p>
<p>---</p>
<p>{sceb_manager_name}</p>''',
            },
        ),
    ]
