# Generated by Django 4.2.20 on 2025-09-09 16:03

from django.db import migrations
from osis_mail_template import MailTemplateMigration

from parcours_doctoral.mail_templates.private_public_defenses import *


class Migration(migrations.Migration):
    dependencies = [
        (
            "parcours_doctoral",
            "0042_thesis_distribution_authorization_mail_templates",
        ),
    ]

    operations = [
        MailTemplateMigration(
            PARCOURS_DOCTORAL_EMAIL_PRIVATE_PUBLIC_DEFENSES_AUTHORISATION,
            {
                'en': 'Private defence authorisation for {student_first_name} {student_last_name}',
                'fr-be': 'Défense privée autorisée {student_first_name} {student_last_name}',
            },
            {
                'en': '''\
<p>Dear {student_first_name} {student_last_name},</p>
<p>Your PhD Field Committee takes note that the private and public defences for your {training_title} will take place on {private_defense_date} and {public_defense_date} respectively.</p>
<p>Please contact us should you require further information.</p>
<p>Sincerely,</p>
<p>{sender_name} - {management_entity_name}</p>''',
                'fr-be': '''\
<p>Cher, Chère, Cher.ère {student_first_name} {student_last_name},</p>
<p>La Commission doctorale de votre domaine prend note que votre défense privée et votre soutenance publique pour  votre {training_title} auront lieu respectivement le {private_defense_date} et le {public_defense_date}.</p>
<p>Nous restons à votre disposition pour tout autre renseignement complémentaire.</p>
<p>Bien cordialement.</p>
<p>---</p>
<p>{sender_name} - {management_entity_name}</p>''',
            },
        ),
        MailTemplateMigration(
            PARCOURS_DOCTORAL_EMAIL_PRIVATE_PUBLIC_DEFENSES_JURY_INVITATION,
            {
                'en': 'Private defence invitation for {student_first_name} {student_last_name}',
                'fr-be': 'Convocation défense privée {student_first_name} {student_last_name}',
            },
            {
                'en': '''\
<p>Dear {jury_member_first_name} {jury_member_last_name},</p>
<p>{student_first_name} {student_last_name} will present the private defence on {private_defense_date} in room {private_defense_place} and the public defence on {public_defense_date} in room {public_defense_place} for {training_title}.</p>
<p>Prior to the public defence, the board will meet in room {deliberation_room}.</p>
<p>Please note that as a board member, your presence is required in person or by videoconference.</p>
<p>Further details will be sent to you at a later date concerning your reception and the day's practical organisation.</p>
<p>Thank you in advance for your important contribution.</p>
<p>Please contact me should you require further information.</p>
<p>Sincerely,</p>
<p>{sender_name} - {management_entity_name}</p>''',
                'fr-be': '''\
<p>Cher, Chère, Cher.ère {jury_member_first_name} {jury_member_last_name},</p>
<p>{student_first_name} {student_last_name} présentera sa défense privée le {private_defense_date}, dans le local {private_defense_place}, ainsi que sa soutenance publique le {public_defense_date}, dans le local {public_defense_place}, pour son {training_title}.</p>
<p>Préalablement à la soutenance publique, le jury se réunira au local {deliberation_room}.</p>
<p>Nous vous rappelons qu'en tant que membre du jury, votre présence est requise physiquement ou en visioconférence.</p>
<p>De plus amples détails vous parviendront ultérieurement concernant votre accueil et l'organisation pratique de cette journée.</p>
<p>En vous remerciant d'avance pour votre contribution importante, je vous adresse mes plus cordiales
salutations et reste bien entendu à votre entière disposition.</p>
<p>---</p>
<p>{sender_name} - {management_entity_name}</p>''',
            },
        ),
        MailTemplateMigration(
            PARCOURS_DOCTORAL_EMAIL_PRIVATE_PUBLIC_DEFENSES_ON_SUCCESS,
            {
                'en': 'PhD awarded',
                'fr-be': 'Obtention du grade de doctorat',
            },
            {
                'en': '''\
<p>Dear {student_first_name} {student_last_name},</p>
<p>Congratulations on earning your degree in {training_title}.</p>
<p>To view the minutes of your public defence, please click on this link <a href="{parcours_doctoral_link_front_public_defense_minutes}">{parcours_doctoral_link_front_public_defense_minutes}</a>.</p>
<p>We will contact you when your diploma is available for collection.</p>
<p>Please contact us should you require further information.</p>
<p>Sincerely,</p>
<p>{sender_name} - {management_entity_name}</p>''',
                'fr-be': '''\
<p>Cher, Chère, Cher.ère {student_first_name} {student_last_name},</p>
<p>Nous tenons à vous féliciter pour l’obtention de votre grade de {training_title}.</p>
<p>Pour visualiser le procès-verbal de votre soutenance publique, merci de cliquer sur ce lien <a href="{parcours_doctoral_link_front_public_defense_minutes}">{parcours_doctoral_link_front_public_defense_minutes}</a>.</p>
<p>Nous vous recontacterons lorsque votre diplôme sera disponible pour retrait.</p>
<p>Nous restons à votre disposition pour tout autre renseignement complémentaire.</p>
<p>Bien cordialement.</p>
<p>---</p>
<p>{sender_name} - {management_entity_name}</p>''',
            },
        ),
    ]
