# Generated by Django 5.2.8 on 2025-12-01 11:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("parcours_doctoral", "0043_private_public_defenses_mail_templates"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parcoursdoctoral",
            name="status",
            field=models.CharField(
                choices=[
                    ("ADMIS", "ADMIS"),
                    ("EN_ATTENTE_DE_SIGNATURE", "EN_ATTENTE_DE_SIGNATURE"),
                    ("CONFIRMATION_SOUMISE", "CONFIRMATION_SOUMISE"),
                    ("CONFIRMATION_REUSSIE", "CONFIRMATION_REUSSIE"),
                    ("NON_AUTORISE_A_POURSUIVRE", "NON_AUTORISE_A_POURSUIVRE"),
                    ("CONFIRMATION_A_REPRESENTER", "CONFIRMATION_A_REPRESENTER"),
                    ("JURY_SOUMIS", "JURY_SOUMIS"),
                    ("JURY_APPROUVE_CA", "JURY_APPROUVE_CA"),
                    ("JURY_APPROUVE_CDD", "JURY_APPROUVE_CDD"),
                    ("JURY_REFUSE_CDD", "JURY_REFUSE_CDD"),
                    ("JURY_APPROUVE_ADRE", "JURY_APPROUVE_ADRE"),
                    ("JURY_REFUSE_ADRE", "JURY_REFUSE_ADRE"),
                    ("RECEVABILITE_SOUMISE", "RECEVABILITE_SOUMISE"),
                    ("RECEVABILITE_A_RECOMMENCER", "RECEVABILITE_A_RECOMMENCER"),
                    ("RECEVABILITE_REUSSIE", "RECEVABILITE_REUSSIE"),
                    ("RECEVABILITE_EN_ECHEC", "RECEVABILITE_EN_ECHEC"),
                    ("DEFENSE_PRIVEE_SOUMISE", "DEFENSE_PRIVEE_SOUMISE"),
                    ("DEFENSE_PRIVEE_AUTORISEE", "DEFENSE_PRIVEE_AUTORISEE"),
                    ("DEFENSE_PRIVEE_A_RECOMMENCER", "DEFENSE_PRIVEE_A_RECOMMENCER"),
                    ("DEFENSE_PRIVEE_REUSSIE", "DEFENSE_PRIVEE_REUSSIE"),
                    ("DEFENSE_PRIVEE_EN_ECHEC", "DEFENSE_PRIVEE_EN_ECHEC"),
                    ("SOUTENANCE_PUBLIQUE_SOUMISE", "SOUTENANCE_PUBLIQUE_SOUMISE"),
                    ("SOUTENANCE_PUBLIQUE_AUTORISEE", "SOUTENANCE_PUBLIQUE_AUTORISEE"),
                    (
                        "DEFENSE_ET_SOUTENANCE_SOUMISES",
                        "DEFENSE_ET_SOUTENANCE_SOUMISES",
                    ),
                    (
                        "DEFENSE_ET_SOUTENANCE_AUTORISEES",
                        "DEFENSE_ET_SOUTENANCE_AUTORISEES",
                    ),
                    ("PROCLAME", "PROCLAME"),
                    ("ABANDON", "ABANDON"),
                ],
                default="ADMIS",
                max_length=64,
                verbose_name="Status",
            ),
        ),
    ]
