# Generated by Django 5.2.8 on 2025-11-21 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parcours_doctoral", "0045_alter_cddmailtemplate_identifier"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="authors",
            field=models.TextField(blank=True, default="", verbose_name="Authors"),
        ),
    ]
