# Generated by Django 5.2.9 on 2025-12-19 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admission", "0279_doctorate_faculty_decision_emails"),
        ("parcours_doctoral", "0046_alter_activity_authors"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parcoursdoctoral",
            name="reference",
            field=models.BigIntegerField(
                editable=False,
                unique=True,
                verbose_name="Reference",
                null=True,  # Make it nullable to migrate the data on reverse migration (0048)
            ),
        ),
        migrations.AddField(
            model_name="parcoursdoctoral",
            name="admission_approved_by_cdd_at",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="Admission approved by CDD at",
            ),
        ),
        migrations.AddField(
            model_name="parcoursdoctoral",
            name="admission_type",
            field=models.CharField(
                choices=[
                    ("ADMISSION", "ADMISSION"),
                    ("PRE_ADMISSION", "PRE_ADMISSION"),
                ],
                db_index=True,
                max_length=255,
                null=True,  # Nullable to initialize the field with a migration (0048)
                verbose_name="Admission type",
            ),
        ),
        migrations.AlterField(
            model_name="parcoursdoctoral",
            name="admission",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="admission.doctorateadmission",
                verbose_name="Admission",
            ),
        ),
    ]
