# Generated by Django 5.2.11 on 2026-02-12 14:34

import django.contrib.postgres.fields
from django.db import migrations, models
from osis_mail_template import MailTemplateMigration

import parcours_doctoral.ddd.formation.domain.model.enums


class Migration(migrations.Migration):

    dependencies = [
        ("parcours_doctoral", "0046_alter_activity_authors"),
    ]

    operations = [
        migrations.AddField(
            model_name="cddconfiguration",
            name="enabled_categories",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                default=parcours_doctoral.ddd.formation.domain.model.enums.CategorieActivite.get_names,
                size=None,
                verbose_name="Enabled categories",
            ),
        ),
        migrations.AlterField(
            model_name="activity",
            name="organizing_institution",
            field=models.CharField(
                blank=True,
                default="",
                max_length=100,
                verbose_name="Organising institutions",
            ),
        ),
        MailTemplateMigration(
            'osis-parcours-doctoral-doctoral-training-promoter-refused-student',
            {
                'en': '[OSIS] A doctoral training activity has been refused',
                'fr-be': "[OSIS] Une activité de formation doctorale a été refusée",
            },
            {
                'en': '''<p>Hello,</p>

    <p>
        The submitted doctoral training activity entitled <em>{activity_title}</em> for your {training_title} has been refused by your promoter,
        you can review all activities by following this link: {parcours_doctoral_link_front_doctoral_training}.

        Here's the reason for this refusal: {reason}
    </p>

    <p>
        ---<br/>
        The OSIS Team
    </p>
    ''',
                'fr-be': '''<p>Bonjour,</p>

    <p>
        L'activité de formation doctorale soumise intitulée <em>{activity_title}</em> pour votre {training_title} a été refusée par votre promoteur.rice,
        vous pouvez la consulter en suivant ce lien : {parcours_doctoral_link_front_doctoral_training}.

        La raison invoquée pour ce refus : {reason}
    </p>

    <p>
        ---<br/>
        L'équipe OSIS
    </p>
    ''',
            },
        ),
    ]
