# Generated by Django 5.2.9 on 2025-12-19 14:48

from django.db import migrations
from django.db.models import F


def copy_admission_data_fields(apps, _):
    ParcoursDoctoral = apps.get_model('parcours_doctoral', 'ParcoursDoctoral')

    doctorates = ParcoursDoctoral.objects.filter(admission__isnull=False).select_related('admission')

    for doctorate in doctorates:
        doctorate.admission_approved_by_cdd_at = doctorate.admission.approved_by_cdd_at
        doctorate.admission_type = doctorate.admission.type

    ParcoursDoctoral.objects.bulk_update(
        doctorates,
        fields=['admission_approved_by_cdd_at', 'admission_type'],
    )


def reset_reference(apps, _):
    ParcoursDoctoral = apps.get_model('parcours_doctoral', 'ParcoursDoctoral')

    doctorates = ParcoursDoctoral.objects.filter(admission__isnull=False).annotate(
        admission_reference=F('admission__baseadmission_ptr__reference')
    )

    for doctorate in doctorates:
        doctorate.reference = doctorate.admission_reference

    ParcoursDoctoral.objects.bulk_update(
        doctorates,
        fields=['reference'],
    )


class Migration(migrations.Migration):
    dependencies = [
        ("admission", "0279_doctorate_faculty_decision_emails"),
        ("parcours_doctoral", "0047_make_admission_facultative_1"),
    ]

    operations = [
        migrations.RunPython(
            code=copy_admission_data_fields,
            reverse_code=reset_reference,
        ),
    ]
