# Generated by Django 5.2.9 on 2026-02-04 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0723_delete_learningunitenrollment"),
        ("parcours_doctoral", "0049_make_admission_facultative_3"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="student",
            constraint=models.UniqueConstraint(
                fields=("person",),
                name="unique_doctorate_student",
            ),
        ),
    ]
