# Generated by Django 5.2.11 on 2026-03-04 11:42

import django.contrib.postgres.fields
import parcours_doctoral.models.cdd_config
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parcours_doctoral", "0051_mail_template_promoter_refusal"),
    ]

    operations = [
        migrations.AddField(
            model_name="cddconfiguration",
            name="conference_communication_types",
            field=parcours_doctoral.models.cdd_config.TranslatedMultilineField(
                default=parcours_doctoral.models.cdd_config.default_communication_types,
                verbose_name="CONFERENCE COMMUNICATION types",
            ),
        ),
        migrations.AlterField(
            model_name="cddconfiguration",
            name="enabled_categories",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(
                    choices=[
                        ("CONFERENCE", "CONFERENCE"),
                        ("COMMUNICATION", "COMMUNICATION"),
                        ("SEMINAR", "SEMINAR"),
                        ("PUBLICATION", "PUBLICATION"),
                        ("SERVICE", "SERVICE"),
                        ("RESIDENCY", "RESIDENCY"),
                        ("VAE", "VAE"),
                        ("COURSE", "COURSE"),
                        ("PAPER", "PAPER"),
                    ]
                ),
                default=parcours_doctoral.models.cdd_config.get_default_enabled_categories,
                size=None,
                verbose_name="Enabled categories",
            ),
        ),
    ]
