# Generated by Django 5.2.12 on 2026-04-08 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "parcours_doctoral",
            "0052_cddconfiguration_conference_communication_types_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="type",
            field=models.TextField(
                blank=True, default="", verbose_name="Activity type"
            ),
        ),
    ]
